feat: add storefront to app server communication
shopware/docs pull request #1014
Opened 2023-07-24 15:16 UTC by shyim

2023-07-25 14:19 UTC, JoshuaBehrens commented
This will add so much to cookie and data security topics :/

2023-07-26 08:40 UTC, sushmangupta commented on guides/plugins/apps/clientside-to-app-backend.md
> +```
@shyim , Currently, Gibook doesn't support mermaid conversions. Can you please provide a jpeg image as an alternative ?

2023-07-26 16:05 UTC, sushmangupta requested changes

2023-07-26 16:05 UTC, sushmangupta commented on guides/plugins/apps/clientside-to-app-backend.md
> +To give some context to the request from the browser directly to the app backend, we allow generating a JWT token that contains session information as claims and is signed by the shop.
```suggestion
Direct communication from the browser to the app backend involves generating a JWT token. This token contains session-specific information, as [claims](#the-jwt-token), and is securely signed by the shop. This mechanism ensures a secure exchange of data between the client and the app backend.
```

2023-07-28 15:07 UTC, sushmangupta commented on guides/plugins/apps/clientside-to-app-backend.md
> +```
Ignore the above comment. Gitbook now supports mermaid plugin 👍

2023-08-03 12:16 UTC, shyim commented
@JoshuaBehrens 

it has nothing to do with cookies (we don't have some, everything stateless), but data security topics you will anyhow have.

2023-08-03 12:17 UTC, sushmangupta approved these changes

2023-08-03 12:17 UTC, merged