Update directory diagram for extended administration modules
shopware/docs pull request #1037
Opened 2023-07-31 14:48 UTC by sushmangupta

This is related to issue : #519

2023-08-02 14:15 UTC, bojanrajh requested changes

2023-08-02 14:15 UTC, bojanrajh commented on guides/plugins/plugins/administration/add-new-tab.md
> +│       └── view
It [seems](https://github.com/shopware/docs/blob/d943dd224897e59fe4fdc05b28d44fa3a3b00924/guides/plugins/plugins/administration/add-new-tab.md#creating-your-new-component) like `view` needs to be on the same level as `page` - please, revert changes in indentation for `view`, and keep the indentation as it is for `sw-product-detail-custom` (as it was fixed correctly).

2023-08-03 09:28 UTC, sushmangupta commented on guides/plugins/plugins/administration/add-new-tab.md
> +│   └──page
@seggewiss , The actual path seems to be this `src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/sw-product-detail.html.twig` . Should I include also include `modules/sw-product` after src directory?

2023-08-03 09:28 UTC, sushmangupta commented on guides/plugins/plugins/administration/add-new-tab.md
> +│    └── sw-product-detail-custom
There is no directory named `sw-product-detail-custom`. Hope that's just an example name.

2023-08-03 09:28 UTC, sushmangupta commented on guides/plugins/plugins/administration/add-new-tab.md
> +│        ├── index.js
Added `index.js`, hope that's fine.

2023-08-03 12:09 UTC, bojanrajh approved these changes

2023-08-03 12:10 UTC, merged