Organize B2B topics & update info for few articles
shopware/docs pull request #1041
Opened 2023-08-04 09:31 UTC by sushmangupta

2023-08-17 12:16 UTC, Haberkamp commented on products/extensions/b2b/b2b-components/employee-management/guides/b2b-employee-invite-registration.md
We have this documented in our stoplight documentation? Is this enough? Then we do not need extra guide, which would just explain the same concept just in another way.

2023-08-23 14:49 UTC, sushmangupta commented on products/extensions/b2b/b2b-components/employee-management/guides/b2b-employee-invite-registration.md
> +//TODO more info required here
```suggestion
Employees can be created via storefront and api to get an invite mail. This has to be later confirmed by the employee to set a password.
```

2023-09-22 04:55 UTC, LarsKemper approved these changes

2023-09-22 06:17 UTC, King-of-Babylon reviewed
Only a few upper and lower case comments :blush:

2023-09-22 06:17 UTC, King-of-Babylon commented on products/extensions/b2b/README.md
> +Unlike the B2B Suit, the B2B Components aim to provide a flexible set of B2B-related features. This enables B2B merchants to deliver the experience they want to their business partners. This is achie
```suggestion
Unlike the B2B Suite, the B2B Components aim to provide a flexible set of B2B-related features. This enables B2B merchants to deliver the experience they want to their business partners. This is achieved by providing abilities that allow B2B Merchants to conduct basic B2B jobs and enable agencies to extend the Components according to the merchant's specific requirements.
```

2023-09-22 06:17 UTC, King-of-Babylon commented on products/extensions/b2b/b2b-components/employee-management/concept/README.md
> +This section includes are the concepts related to Employee management.
```suggestion
This section includes are the concepts related to Employee Management.
```

2023-09-22 06:17 UTC, King-of-Babylon commented on products/extensions/b2b/b2b-components/employee-management/guides/README.md
> +The following articles gives you an idea of roles. Also it guides you on creating your own permissions via app or plugin for the b2b employee management component.
```suggestion
The following articles gives you an idea of roles. Also it guides you on creating your own permissions via app or plugin for the B2B Employee Management component.
```

2023-09-22 06:17 UTC, King-of-Babylon commented on products/extensions/b2b/b2b-components/employee-management/guides/b2b-permissions/README.md
> +Use permissions to restrict access to certain information or functionalities within the B2B components. For example, the B2B supervisor can restrict which employee can manage the company's employee a
```suggestion
Use permissions to restrict access to certain information or functionalities within the B2B Components. For example, the B2B supervisor can restrict which employee can manage the company's employee accounts.
```

2023-09-22 06:17 UTC, King-of-Babylon commented on products/extensions/b2b/b2b-components/employee-management/guides/b2b-permissions/README.md
> +The following permissions are already included and used in the B2B employee management component. More "base" permissions will be duly added with future B2B Components.
```suggestion
The following permissions are already included and used in the B2B Employee Management component. More "base" permissions will be duly added with future B2B Components.
```

2023-09-22 06:17 UTC, King-of-Babylon commented on products/extensions/b2b/b2b-components/employee-management/guides/b2b-roles.md
> +The Business partner has the opportunity to create a “default” role that will be selected by default, when creating a new employee.
```suggestion
The business partner has the opportunity to create a “default” role that will be selected by default, when creating a new employee.
```

2023-09-22 08:27 UTC, King-of-Babylon approved these changes

2023-09-22 09:52 UTC, bojanrajh requested changes
Content looks good.

Please, add [redirects](https://github.com/shopware/docs/blob/master/.gitbook.yaml) for all the articles that were moved:
 - `products/extensions/b2b-suite/*: products/extensions/b2b/b2b-suite/*`
 - `...`

2023-09-22 13:18 UTC, LarsKemper commented
> Content looks good.
> 
> Please, add [redirects](https://github.com/shopware/docs/blob/master/.gitbook.yaml) for all the articles that were moved:
> 
> * `products/extensions/b2b-suite/*: products/extensions/b2b/b2b-suite/*`
> * `...`

For the redirects doesn't work at all. Event the existing ones are redirecting me to the 404 page
For example:

2023-09-27 04:07 UTC, Isengo1989 commented
@LarsKemper I guess there was still old code/urls from gitbook, since we moved recently to devhub there was a change in the URL path endings, @bojanrajh fixed this recently.

https://github.com/shopware/docs/commit/732c446c6827cfcc7aa938b9967d8cd6d1fb2315

Those redirects work now. Could you take another look?

2023-09-27 06:09 UTC, King-of-Babylon commented
> @LarsKemper I guess there was still old code/urls from gitbook, since we moved recently to devhub there was a change in the URL path endings, @bojanrajh fixed this recently.
> 
> [732c446](https://github.com/shopware/docs/commit/732c446c6827cfcc7aa938b9967d8cd6d1fb2315)
> 
> Those redirects work now. Could you take another look? If you need help, let me know (but you probably know better what was moved. If you pass me a list, I can look into it as well)

Hi @Isengo1989,

I guess the redirects should look like that:

- products/extensions/b2b-components/employee-management/concept/index.md: products/extensions/b2b/b2b-components/employee-management/concept/README.md

- products/extensions/b2b-components/employee-management/guides/creating-own-permissions-via-app.md: products/extensions/b2b/b2b-components/employee-management/guides/b2b-permissions/creating-own-permissions-via-app.md

- products/extensions/b2b-components/employee-management/guides/index.md: products/extensions/b2b/b2b-components/employee-management/guides/README.md

- products/extensions/b2b-components/employee-management/index.md: products/extensions/b2b/b2b-components/employee-management/README.md

- products/extensions/b2b-components/index.md: products/extensions/b2b/b2b-components/README.md

- products/extensions/b2b-suite/guides/administration/index.md: products/extensions/b2b/b2b-suite/guides/administration/README.md

2023-10-17 08:56 UTC, Isengo1989 commented
@bojanrajh I rebased it and adjusted the mentioned topics. Please check the redirects (question about wildcards - slack)

2023-10-25 10:10 UTC, merged