Update flow builder actions docs for 6.4
shopware/docs pull request #1080
Opened 2023-08-24 01:59 UTC by nguyenky

This is an update of the Flow Builder actions document for `6.4.x` version.
Issue link: https://github.com/shopware/docs/issues/948

2023-08-30 13:14 UTC, sushmangupta requested changes

2023-08-30 13:14 UTC, sushmangupta commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +```
```suggestion
```
{%endcode%}
```

2023-08-30 13:14 UTC, sushmangupta commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
>  {% raw %}
```suggestion
{% code title="<plugin root>/src/Resources/app/administration/src/component/sw-flow-create-tag-modal/sw-flow-create-tag-modal.html.twig" %}
```

2023-08-30 13:22 UTC, sushmangupta commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +</service>
```suggestion
</service>
```

{% endcode %}
```

2023-08-30 13:23 UTC, sushmangupta requested changes

2023-08-30 13:23 UTC, sushmangupta commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +</service>
```suggestion
    <tag name="flow.action" priority="600"/>
</service>
```

{% endcode %}
```

2023-08-31 06:37 UTC, nguyenky commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +</service>
I updated it

2023-09-01 07:43 UTC, Isengo1989 commented
@sushmangupta tested with 6.4.19.0 - looks good :+1:

2023-09-01 07:51 UTC, Isengo1989 approved these changes

2023-09-06 08:39 UTC, sushmangupta approved these changes
@nguyenky , thanks for updating this info to our docs :)

2023-09-06 08:39 UTC, merged