NEXT-30116 - Document for B2B Customer Specific Features
shopware/docs pull request #1139
Opened 2023-10-16 03:30 UTC by nguyenytran

Document for B2B Customer Specific Feature.

2023-10-17 12:18 UTC, Isengo1989 commented
@nguyenytran I added some comments with some corrections (since I can not edit it directly)

2023-10-18 02:53 UTC, nguyenytran commented
> @nguyenytran I added some comments with some corrections (since I can not edit it directly)

2023-10-18 02:55 UTC, nguyenytran commented
> @nguyenytran I added some comments with some corrections (since I can not edit it directly)

Hi @Isengo1989, I don't see your comments.

2023-10-18 07:36 UTC, Isengo1989 requested changes

2023-10-18 08:33 UTC, merged