NEXT-30083 - Documentation for Quotes
shopware/docs pull request #1249
Opened 2024-01-11 09:23 UTC by leduc92

2024-02-27 14:21 UTC, sushmangupta requested changes
Please take a look at these suggestions.

2024-02-27 14:21 UTC, sushmangupta commented on products/extensions/b2b-components/quotes-management/index.md
> +Partners have the freedom to accept or decline the offer, and upon acceptance, they are guided through the seamless checkout process. The system then automatically generates an order based on the acc
```suggestion
The Quote Management feature streamlines the B2B partnership process by enabling partners to seamlessly request and accept quotes without the need for time-consuming manual negotiations. The process begins with B2B partners populating their cart with desired products, after which they can initiate a quote request based on the contents of their cart. Once the request is submitted, B2B merchants have the ability to review the quote within the administration system. They can also apply discounts to individual product items within the quote to tailor the offer to the partner's needs. Subsequently, the modified quote is sent to the B2B partners for their consideration.

Partners are free to accept or decline the offer, and upon acceptance, they are guided through the seamless checkout process. The system then automatically generates an order based on the accepted quote, optimizing efficiency and ensuring a smooth transition from negotiation to transaction. This feature revolutionizes B2B interactions by reducing the need for extensive manual discussions and fostering a more efficient and collaborative environment for both partners and merchants.
```

2024-02-27 14:21 UTC, sushmangupta commented on products/extensions/b2b-components/quotes-management/quotes-conversion.md
> +We allow customers to convert their shopping carts into quotes to facilitate seamless processing. We introduce 2 new services to handle the conversion process
```suggestion
Customers can convert their shopping carts into quotes to facilitate seamless processing. There are two new services to handle the conversion process :
```

2024-02-27 14:21 UTC, sushmangupta commented on products/extensions/b2b-components/quotes-management/quotes-conversion.md
> +**Cart to quote converter:**
```suggestion
## Cart to quote converter
```

2024-02-27 14:21 UTC, sushmangupta commented on products/extensions/b2b-components/quotes-management/quotes-conversion.md
> +When a customer wants to request a quote from their shopping cart, we basically convert a cart to an order, then process to enrich the data for quote. the method `convertToQuote` of class `Shopware\C
```suggestion
When a customer wants to request a quote for their shopping cart, the process involves converting a cart to an order and then proceeding to enrich the data for the quote. The method `convertToQuote` of class `Shopware\Commercial\B2B\QuoteManagement\Domain\CartToQuote\CartToQuoteConverter` is responsible for this process.
```

2024-02-27 14:21 UTC, sushmangupta commented on products/extensions/b2b-components/quotes-management/quotes-conversion.md
> +When a customer wants to place an order based on a quote, we will create a new cart based on quote data, the method `convertToCart` of class `Shopware\Commercial\B2B\QuoteManagement\Domain\QuoteToCar
```suggestion
When a customer wants to place an order based on a quote, a new cart is created based on the quote data. The method `convertToCart` of class `Shopware\Commercial\B2B\QuoteManagement\Domain\QuoteToCart\QuoteToCartConverter` is responsible for this process.
```

2024-02-27 14:21 UTC, sushmangupta commented on products/extensions/b2b-components/quotes-management/quotes-conversion.md
> +**Quote to cart converter:**
```suggestion
## Quote to cart converter
```

2024-03-06 09:27 UTC, sushmangupta approved these changes

2024-03-06 10:24 UTC, nguyenky approved these changes

2024-03-06 12:05 UTC, Isengo1989 approved these changes

2024-03-07 03:45 UTC, phuoccx approved these changes

2024-03-07 07:36 UTC, merged

2024-11-05 09:34 UTC, RobinHoutevelts commented
> When a customer wants to request a quote for their shopping cart, the process involves converting a cart to an order and then proceeding to enrich the data for the quote. The method `convertToQuote` of class `Shopware\Commercial\B2B\QuoteManagement\Domain\CartToQuote\CartToQuoteConverter` is responsible for this process.

@leduc92 Can someone point me to this class?
It doesn't seem to exist inside the `shopware/` organization when I [search for it on GitHub.](https://github.com/search?q=org%3Ashopware+CartToQuoteConverter&type=code)

2024-11-05 10:17 UTC, mitelg commented
@RobinHoutevelts the described feature is part of the Commercial plugin, which is separated from the core. if you want to have access to that repo, you can ask our support for it