NEXT-12594 - Add using state machine guide
shopware/docs pull request #125
Opened 2021-03-08 13:43 UTC by PaddyS

2021-03-08 14:37 UTC, shyim approved these changes

2021-03-08 19:05 UTC, mitelg requested changes
what about this helper class? https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Order/Aggregate/OrderTransaction/OrderTransactionStateHandler.php
it is totally missing here

2021-03-08 19:05 UTC, mitelg commented on guides/plugins/plugins/checkout/order/using-the-state-machine.md
> +    '16d5bbd005434d71b45f4b18b9932502',
here you use a real ID, in the examples above only a placeholder

2021-03-08 19:05 UTC, mitelg commented on guides/plugins/plugins/checkout/order/using-the-state-machine.md
> +Then it's creating a new `Criteria` object and adds a filter in order to only search for `order_delivery´ entities, whose
```suggestion
Then it's creating a new `Criteria` object and adds a filter in order to only search for `order_delivery` entities, whose
```

2021-03-09 13:23 UTC, PaddyS commented on guides/plugins/plugins/checkout/order/using-the-state-machine.md
> +Each of those comes with several possible values, e.g. for the transactions some of those are: "open", "reopen", "cancel", "chargeback" etc.
Found it [here](https://github.com/shopware/platform/blob/trunk/src/Core/System/StateMachine/Aggregation/StateMachineTransition/StateMachineTransitionActions.php) and in my database. 🤔

2021-03-09 13:32 UTC, PaddyS commented on guides/plugins/plugins/checkout/order/using-the-state-machine.md
> +Each of those comes with several possible values, e.g. for the transactions some of those are: "open", "reopen", "cancel", "chargeback" etc.
Oh, yeah, I kinda confused those while developing as well. There is a difference between the action names (the ones you need to use) and the state names. E.g. "do_pay" is the action, while "in_progress" is the state afterwards.

I tested chargeback once more and it really didn't work, yet it's a valid action due to the database. Weird.
Removed it.

2021-03-09 13:34 UTC, PaddyS commented
> what about this helper class? https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Order/Aggregate/OrderTransaction/OrderTransactionStateHandler.php
> it is totally missing here

@mitelg Yeah, right. But afaik it's only available for the order transaction states and it felt weird to document like "Oh, also we've got a helper for that, but just for the transactions..."

Still think it's a good idea to add it?

2021-03-09 19:52 UTC, mitelg commented
yes please 😁👍 
it is even not used in the core 🙈 

one could argue, why is it still there and not deprecated/removed? but still it is used in most payment plugins

2021-03-12 12:52 UTC, mitelg approved these changes

2021-03-15 10:48 UTC, merged