Add readme file
shopware/docs pull request #1282
Opened 2024-02-06 15:27 UTC by Isengo1989

Add Readme file for better communication and problem solving

2024-02-06 17:02 UTC, elkmod requested changes
Just small adjustments, which will improve the reading flow.

2024-02-06 17:02 UTC, elkmod commented on README.md
> +- represents the content of https://developer.shopware.com/docs/
```suggestion
This repository contains general **developer** documentation for Shopware 6 which is served on [developer.shopware.com/docs](https://developer.shopware.com/docs/). The root of our developer portal [developer.shopware.com](https://developer.shopware.com/) is reflected by the [developer portal](https://github.com/shopware/developer-portal) repository.
```

2024-02-07 09:33 UTC, sushmangupta commented on README.md
> +They are defined in the [`.github/workflows`](./.github/workflows) folder and help the DX team to maintain the documentation. The workflows are triggered by events like `push`, `pull_request`, `sched
```suggestion
They are defined in the [`.github/workflows`](./.github/workflows) folder and help the DX team to maintain the documentation. The workflows are triggered by events like `push`, `pull_request`, `schedule` and `workflow_dispatch`. The workflows are used to build, test, and deploy the documentation. If a PR pipeline fails, the PR will be marked as failed, and it won't be possible to merge it. In this case, check the below-mentioned workflows to see what went wrong and where to fix it.
```

2024-02-07 13:20 UTC, sushmangupta requested changes

2024-02-07 13:20 UTC, sushmangupta commented on README.md
> +Using [lychee](https://github.com/lycheeverse/lychee) to validate external links.
```suggestion
### Validate external links

[Lychee](https://github.com/lycheeverse/lychee) is used to check if external links are working properly or broken. The configuration for lychee can be found in [`validate-external-links.yml`](./.github/workflows/validate-external-links.yml).
```

2024-02-07 13:26 UTC, sushmangupta commented
May I know what these tags are meant for : https://github.com/shopware/docs/tags ?

2024-02-09 09:42 UTC, merged