NEXT-12716 - Add guide on how to remove a javascript plugin
shopware/docs pull request #132
Opened 2021-03-09 15:39 UTC by leichteckig

What should be done?
Create a new article on our GitBook instance which explains how to remove unwanted javascript plugin / prevent them from being loaded in the first place.

This article should mention:

The prerequisite, a working plugin (Refer to the plugin base guide)
Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
A short code example, including an explanation, on how to do it
Category: Extensions > Plugins > Storefront

Are there already guides in the previous documentation for this?
Unfortunately, No. But please have a look at our example guide(e.g. note the PLACEHOLDERs for cross-references, that do not exist yet) and the Writing guidelines.

For more information, ask me, Patrick Stahl.

2021-03-09 15:47 UTC, NiklasLimberg requested changes

2021-03-09 15:47 UTC, NiklasLimberg commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +don't want a Core plugin to interfere. This guide will teach you how to remove the unnecessary Javascript plugin from
```suggestion
don't want a Core plugin to interfere, with your own code. This guide will teach you how to remove the unnecessary Javascript plugin from
```

2021-03-09 15:47 UTC, NiklasLimberg commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +beforehand might help you understand this guide a bit further.
```suggestion
While this is not mandatory, having read the guide about [adding custom javascript plugins](./add-custom-javascript.md) beforehand might help you understand this guide a bit further. 
```

2021-03-09 15:47 UTC, NiklasLimberg commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +{% code title="<plugin root>/<plugin root>src/Resources/app/storefront/src/main.js" %}
```suggestion
{% code title="<plugin root>/src/Resources/app/storefront/src/main.js" %}
```

2021-03-09 15:47 UTC, NiklasLimberg commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +testing the removal of the unnecessary plugin is using your browser's devtools. Just open your devtool's console and
```suggestion
After building the storefront anew, you shouldn't be able to open the offcanvas cart anymore. Another useful way of
testing this is using your browser's devtools. Just open your devtool's console and 
```

2021-03-09 15:47 UTC, NiklasLimberg commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +testing the removal of the unnecessary plugin is using your browser's devtools. Just open your devtool's console and
U don't have to apply this if u dont want to

2021-03-10 08:45 UTC, tobiasberge commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +# Remove unnecessary Javascript plugin
Tbh I'm not sure about the "unnecessary". To me it sounds a bit have you have to remove a plugin which was unnecessary in the first place. Maybe just "Remove a Javascript plugin"

2021-03-10 08:56 UTC, lernhart requested changes

2021-03-10 08:56 UTC, lernhart commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +your one plugin.
```suggestion
your own plugin.
```

2021-03-10 08:56 UTC, lernhart commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +Imagine we want to exclude the `OffcanvasCart` plugin, just to get a test case which can be inspected easily.
```suggestion
Imagine we want to exclude the `OffCanvasCart` plugin, just to get a test case which can be inspected easily.
```

2021-03-10 08:56 UTC, lernhart commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +In our case, we shouldn't find `OffcanvasCart` in the listed plugins anymore.
```suggestion
In our case, we shouldn't find `OffCanvasCart` in the listed plugins anymore.
```

2021-03-10 10:02 UTC, tobiasberge requested changes
See my comment about "unnecessary"

2021-03-12 08:49 UTC, PaddyS requested changes

2021-03-12 08:49 UTC, PaddyS commented on guides/plugins/plugins/storefront/remove-unnecessary-js-plugin.md
> +your own Shopware plugin.
```suggestion
don't want a Core plugin to interfere, with your own code. This guide will teach you how to remove this Javascript plugin with
your own Shopware plugin.
```

2021-03-12 14:39 UTC, NiklasLimberg approved these changes

2021-03-15 12:13 UTC, PaddyS requested changes
Rebase

2021-03-15 14:07 UTC, merged