NEXT-33884 - quickfixes for Meteor Admin SDK
shopware/docs pull request #1323
Opened 2024-03-08 07:39 UTC by jleifeld

The current documentation has outdated parts in terms of developing apps for administration. This PR isn't going to rewrite everything to use our recommended way of extending applications, the Meteor Admin SDK. Instead, it only contains some small quickfixes and wins. This is to make it clearer to the reader that the current articles are only suitable for extremely small applications.

It also contains some structure fixes, e.g. moving the CMS Element creation article to the correct apps directory instead of the plugins directory, adding a small article at the beginning of each article in the admin app series, etc.

2024-03-08 08:29 UTC, bojanrajh approved these changes
I'm approving this changes until we merge https://github.com/shopware/developer-portal/pull/197 and https://github.com/shopware/meteor/pull/53 (see [preview](https://developer-documentation-hjegedpa8-shopware-frontends.vercel.app/resources/admin-extension-sdk/)). Then we'll also check for old links in our docs.

2024-03-08 08:31 UTC, bojanrajh requested changes
Actually, there's one thing to fix: https://github.com/shopware/developer-portal/actions/runs/8200236466/job/22426620596#step:7:27

2024-03-08 10:32 UTC, sushmangupta approved these changes

2024-03-11 07:57 UTC, bojanrajh approved these changes

2024-03-11 08:20 UTC, jleifeld commented
> I'm approving this changes until we merge [shopware/developer-portal#197](https://github.com/shopware/developer-portal/pull/197) and [shopware/meteor#53](https://github.com/shopware/meteor/pull/53) (see [preview](https://developer-documentation-hjegedpa8-shopware-frontends.vercel.app/resources/admin-extension-sdk/)). Then we'll also check for old links in our docs.

Sounds good!

@sushmangupta Thanks for fixing the text to matching the style guide 🙂

2024-03-11 14:02 UTC, merged