NEXT-12785 - [NEW] Administration: Add shortcuts
shopware/docs pull request #134
Opened 2021-03-10 10:20 UTC by NiklasLimberg

What should be done?

Create a new article on our GitBook instance which explains how to add a new shortcut to a module.

This article should mention:

-The prerequisite, a working plugin (Refer to the plugin base guide)
- Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
- A short code example, including an explanation, on how to do it
- Maybe this should be built upon the "Add module" guide. If so, please add this reference as a prerequisite.

Category: Extensions > Plugins > Administration
Are there already guides in the previous documentation for this?

Unfortunately, No. But please have a look at our example guide(e.g. note the PLACEHOLDERs for cross-references, that do not exist yet) and the Writing guidelines.

For more information, ask me, Patrick Stahl.

2021-03-10 10:29 UTC, lernhart requested changes

2021-03-10 10:29 UTC, lernhart commented on guides/plugins/plugins/administration/add-shortcuts.md
> +## Adding Shortcuts
Should'nt it be: ?
```suggestion
# Adding Shortcuts

## Overview 
```

2021-03-10 10:29 UTC, lernhart commented on guides/plugins/plugins/administration/add-shortcuts.md
> +Shortcuts in the Shopware 6 are defined on a Component basis. This guide will show you how.
```suggestion
Shortcuts in Shopware 6 are defined on a Component basis. This guide will show you how.
```

2021-03-10 10:29 UTC, lernhart commented on guides/plugins/plugins/administration/add-shortcuts.md
> +All you need for this guide is a running Shopware 6 instance and full access to both the files.
[...] to both the files **and what** ?

2021-03-10 10:29 UTC, lernhart commented on guides/plugins/plugins/administration/add-shortcuts.md
> +Preferably a registered module and custom component.
Is this a continuation of the previous statement ? 
If so, seperate them by comma or add an **and**

2021-03-10 10:29 UTC, lernhart commented on guides/plugins/plugins/administration/add-shortcuts.md
> +    }
```suggestion
    shortcuts: {
        'SYSTEMKEY+S': {
            active() {
                return this.acl.can('product.editor');
            },
            method: 'myEditProductFunction'
        },
        ESCAPE: 'myCancelEditProductFunction'
    },

   
    methods: {
        function0() {
            console.log("myEditProductFunction")
        },
        function1() {
            console.log("myCancelEditProductFunction")
        }
    }
```

2021-03-10 10:29 UTC, lernhart commented on guides/plugins/plugins/administration/add-shortcuts.md
> +Shortcuts can be registered with the `shortcuts` attribute.
```suggestion
The following code sample will show you how to register shortcuts in your components with help of the `shortcuts` attribute.
```

2021-03-10 10:29 UTC, lernhart commented on guides/plugins/plugins/administration/add-shortcuts.md
> +The first shortcut is only active if the User has the privilege `product.editor`, learn more about ACL and how to add your own ACL rules [here](./add-acl-rules.md).
```suggestion
The first shortcut is only active if the user has the privilege `product.editor`, learn more about ACL and how to add your own ACL rules [here](./add-acl-rules.md).
```

2021-03-10 13:57 UTC, leichteckig requested changes

2021-03-10 13:57 UTC, leichteckig commented on guides/plugins/plugins/administration/add-shortcuts.md
> +Shortcuts in Shopware 6 are defined on a Component basis. This guide will show you how.
```suggestion
Shortcuts in Shopware 6 are defined on a Component basis. This guide will show you how to add your own ones.
```

2021-03-10 14:11 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-shortcuts.md
> +    shortcuts: {
i think that  is pretty  self explanatory with property names and  the sentence that is below

2021-03-10 14:13 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-shortcuts.md
> +  * [Add custom routes](./add-custom-route.md)
```suggestion
* [Writing templates](writing-templates.md)
* [Add custom module](add-custom-module.md)
* [Add menu entry](./add-menu-entry.md)
* [Add custom routes](./add-custom-route.md)
```

2021-03-10 14:26 UTC, leichteckig requested changes

2021-03-10 14:26 UTC, leichteckig commented on guides/plugins/plugins/administration/add-shortcuts.md
> +    shortcuts: {
Don't assume things, this was a great criticism of our old docs. People use the docs to familiarize with shopware so they won't know Shopware's way of shortcuts.

2021-03-10 14:50 UTC, leichteckig approved these changes

2021-03-10 15:12 UTC, lernhart approved these changes

2021-03-11 08:59 UTC, raknison approved these changes

2021-03-11 09:40 UTC, jleifeld approved these changes

2021-03-15 07:34 UTC, JoshuaBehrens requested changes

2021-03-15 07:34 UTC, JoshuaBehrens commented on guides/plugins/plugins/administration/add-shortcuts.md
> +The first keyboard shortcut reacts to the key combination of `SYSTEMKEY+S`, only if the the user has the privilege `product.editor`, with the invocation of the component method with the name `myEditP
How can I know what `SYSTEMKEY` means? Is there a list like `SYSTEMKEY: Windows Ctrl / Apple Cmd` or something like that? What is the key called for Alt/⌥?

2021-03-15 12:34 UTC, raknison approved these changes

2021-03-15 14:10 UTC, JoshuaBehrens approved these changes

2021-03-15 14:10 UTC, JoshuaBehrens commented on guides/plugins/plugins/administration/add-shortcuts.md
> +The first keyboard shortcut reacts to the key combination of `SYSTEMKEY+S`, only if the the user has the privilege `product.editor`, with the invocation of the component method with the name `myEditP
I mean. It is not a list but it is the description I looked for.

2021-03-16 10:43 UTC, merged