NEXT-33933 - Improved employee invitation docs
shopware/docs pull request #1344
Opened 2024-04-08 12:49 UTC by MartinKrzykawski

Updated the employee invitation docs.

Wrote how to invite employee via administration, storefront and store-api and also how to replace the default URL with a custom one.

2024-04-09 10:37 UTC, lukasrump commented on products/extensions/b2b-components/employee-management/guides/b2b-employee-invitation.md
> +Employees can be created via storefront, administration and store-api to get an invitation email. This has to be confirmed by the employee to set a password.
For me this sentence was a bit akward to read. Maybe something like: 
```suggestion
Employees can be created via storefront, administration and store-api. The employee will get an invitation mail that has to be confirmed to set a password.
```

2024-04-09 10:43 UTC, lukasrump approved these changes
Nice work. I added just one optional comment.

2024-04-09 14:55 UTC, sushmangupta commented on products/extensions/b2b-components/employee-management/guides/b2b-employee-invitation.md
> +The default URL for the acceptance is `/account/business-partner/employee/invite/%%RECOVERHASH%%`, the recovery hash is used as a unique identifier and is only valid for the invitation of one employe
```suggestion
# Employee Invitation

Employees can be created via Storefront, Store-api, and Administration. 

- Storefront - Business partners can invite employees by logging-in to Storefront and navigating to the `employee` page. From there, they can add a new employee.
- Store API - One can utilize the `/store-api/employee/create` endpoint while logged in as a customer to invite employees.
- Administration - Merchants can invite employees by logging in to the administration interface. Selects the business partner customer, navigates to the `company` tab, and adds a new employee account in edit mode.

The invited employee receives an invitation mail that must be confirmed to set a password.

## The URL for the invitation acceptance

Upon invitation, the employee will receive an email requiring confirmation to set a password. This process will also activate the employee for the business partners company.
The default URL for the acceptance is `/account/business-partner/employee/invite/%%RECOVERHASH%%`, the recovery hash is used as a unique identifier and is only valid for the invitation of one employee.
```

2024-04-09 14:56 UTC, sushmangupta requested changes
@MartinKrzykawski , please take a look

2024-04-10 06:10 UTC, MartinKrzykawski commented
> @MartinKrzykawski , please take a look

Hey, looks good to me, i commited your provided changes. Thanks! :)

2024-04-10 06:13 UTC, sushmangupta approved these changes
Thank you @MartinKrzykawski for the update!

2024-04-10 06:13 UTC, merged