NEXT-30813 - Checkout gateway
shopware/docs pull request #1387
Opened 2024-05-23 14:55 UTC by lernhart

2024-05-24 08:43 UTC, bojanrajh requested changes

2024-05-24 08:43 UTC, bojanrajh commented on guides/plugins/apps/gateways/checkout/checkout-gateway.md
> +{% page-ref page="app-base-guide.md" %}
Use `<PageRef />` component instead ([example](https://github.com/shopware/docs/blob/3049f905a176b861b3c135490e46885e0a21f088/guides/plugins/index.md?plain=1#L16)).

2024-05-24 08:43 UTC, bojanrajh commented on guides/plugins/apps/gateways/checkout/checkout-gateway.md
> +{% code title="manifest.xml" %}
Use `::: code-group` block instead ([example](https://github.com/shopware/docs/blob/3049f905a176b861b3c135490e46885e0a21f088/guides/plugins/plugins/plugin-fundamentals/logging.md?plain=1#L62), [docs](https://vitepress.dev/guide/markdown#code-groups)).

2024-05-24 08:43 UTC, bojanrajh commented on guides/plugins/apps/gateways/checkout/checkout-gateway.md
> +{% hint style="warning" %}
Use `::: warning` instead ([docs](https://vitepress.dev/guide/markdown#default-title))

2024-05-24 08:43 UTC, bojanrajh commented on guides/plugins/apps/gateways/checkout/checkout-gateway.md
> +{% tabs %}
Use `<Tabs>` component instead ([example](https://github.com/shopware/docs/blob/3049f905a176b861b3c135490e46885e0a21f088/guides/installation/devenv.md?plain=1#L26)).

2024-05-27 07:32 UTC, mstegmeyer approved these changes

2024-05-27 12:20 UTC, bojanrajh approved these changes

2024-05-27 12:21 UTC, merged