NEXT-32862 - Add docs for default FS adapter config fallback
shopware/docs pull request #1395
Opened 2024-06-03 11:24 UTC by keulinho

2024-06-03 11:27 UTC, shyim commented on guides/hosting/infrastructure/filesystem.md
> +This means when you want to change the configuration used for the public filesystem, but the others should use the old configuration you have to set them explicitly.
maybe add an example with yaml anchor to copy the config 🤔

2024-06-05 09:30 UTC, sushmangupta requested changes

2024-06-05 09:30 UTC, sushmangupta commented on guides/hosting/infrastructure/filesystem.md
> +By default, the configuration for the theme, asset and sitemap filesystem will use the configuration from the `public` filesystem, if they are not specifically configured.
```suggestion
By default, the configuration for the theme, asset and sitemap filesystem will use the configuration from the `public` filesystem if they are not specifically configured.
```

2024-06-05 09:30 UTC, sushmangupta commented on guides/hosting/infrastructure/filesystem.md
>  If you want to regulate the uploaded file types, then you could add the keys `allowed_extensions`for the public filesystem or `private_local_download_strategy` for the private filesystem.
```suggestion
If you want to regulate the uploaded file types, then you could add the keys `allowed_extensions` for the public filesystem or `private_local_download_strategy` for the private filesystem.
```

2024-06-19 09:28 UTC, sushmangupta approved these changes
Thank you for the update! :)

2024-06-19 09:30 UTC, merged