NEXT-35970 - Docs for shopping lists
shopware/docs pull request #1396
Opened 2024-06-05 06:03 UTC by nguyenky

2024-06-05 07:12 UTC, bojanrajh requested changes
Should we remove numeric filename prefixes (`nav.position` should be enough for proper placement in the sidebar)?

2024-06-05 07:56 UTC, leduc92 commented on products/extensions/b2b-components/shopping-lists/01-entities-and-schema.md
> +The  Shopping list line item represents a set of products. These products are line items of the shopping list.
It seems like that there're 2 space between The  Shopping

2024-06-05 07:56 UTC, leduc92 commented on products/extensions/b2b-components/shopping-lists/02-api-and-pricing.md
> +# Store API
Should we just create a link to our store API docs? 
https://shopware.stoplight.io/docs/store-api/c9849725606fd-create-new-shopping-list

2024-06-05 07:56 UTC, leduc92 commented on products/extensions/b2b-components/shopping-lists/index.md
> +The Shopping List application is designed to help users easily manage their shopping needs. It allows users to create, edit, and organize their shopping lists efficiently. With features such as item
List with `s`. 

IMO `Shopping Lists  component` is better than the `Shopping Lists  application`

2024-06-05 07:56 UTC, leduc92 commented on products/extensions/b2b-components/shopping-lists/01-entities-and-schema.md
> +The  Shopping list line item represents a set of products. These products are line items of the shopping list.
Shopping Lists

2024-06-05 09:36 UTC, sushmangupta commented on products/extensions/b2b-components/shopping-lists/01-entities-and-schema.md
> +# Entities and schema
@leduc92 , @nguyenky - I would like to discuss about the document structuring w.r.t B2B components.

2024-06-07 07:31 UTC, sushmangupta commented on products/extensions/b2b-components/shopping-lists/01-entities-and-schema.md
> +# Entities and schema
After conversation with Duc and Nam, yesterday. I will rearrange the structure as per this : https://shopware.atlassian.net/browse/DX-592. After that will restructure this PR too.

2024-06-12 13:46 UTC, sushmangupta commented
This PR info has been added in this PR: https://github.com/shopware/docs/pull/1407/files. Hence to avoid duplicity, I will close this.

2024-06-12 13:46 UTC, closed without merging