Add custom approval rule by app
shopware/docs pull request #1397
Opened 2024-06-05 10:21 UTC by quynhnguyen68

2024-06-11 06:35 UTC, bojanrajh approved these changes

2024-06-14 14:03 UTC, sushmangupta requested changes

2024-06-14 14:03 UTC, sushmangupta commented on products/extensions/b2b-components/order-approval/guides/04-add-new-approval-condition.md
> +Script logic is similar to [Add custom rule conditions](../../../../../guides/plugins/apps/rule-builder/add-custom-rule-conditions.md). Let's continue with our example by creating a script file that
script file that compares the current shopping cart's total price against what ?

2024-06-17 03:05 UTC, quynhnguyen68 commented on products/extensions/b2b-components/order-approval/guides/04-add-new-approval-condition.md
> +<<< @/docs/snippets/config/app/approval-rule-conditions.xml
I use it to show sample manifest file

<img width="798" alt="Screenshot 2024-06-15 at 17 10 39" src="https://github.com/shopware/docs/assets/34686861/8d520201-6b6c-43f5-9178-d5d8b1ebad6d">

2024-06-17 03:53 UTC, quynhnguyen68 commented on products/extensions/b2b-components/order-approval/guides/04-add-new-approval-condition.md
> +Script logic is similar to [Add custom rule conditions](../../../../../guides/plugins/apps/rule-builder/add-custom-rule-conditions.md). Let's continue with our example by creating a script file that
@sushmangupta I already edit this sentence 
"Let's continue with our example by creating a script file that compares the current shopping cart's total price with the pre-established value in the approval rule."

2024-06-17 09:38 UTC, sushmangupta approved these changes
Thanks for updating the docs!

2024-06-17 09:39 UTC, merged