NEXT-37038 - Remote thumbnail generation docs
shopware/docs pull request #1425
Opened 2024-06-28 09:26 UTC by tamvt

2024-06-28 12:15 UTC, Isengo1989 commented
@tamvt is this planned for a version already? Can't find it in a current, so I have to flag the version or block it for now.

2024-07-01 03:10 UTC, vienthuong commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +With the pattern set as `{mediaUrl}/{mediaPath}?width={width}&ts={mediaUpdatedAt}`, the resulting URL would be `https://yourshop.example/abc/123/456.jpg?width=80&ts=1718954838`.
```suggestion
For example, with the pattern set as `{mediaUrl}/{mediaPath}?width={width}&ts={mediaUpdatedAt}`, the thumbnail URL would generated as `https://yourshop.example/abc/123/456.jpg?width=80&ts=1718954838`.
```

2024-07-01 03:14 UTC, vienthuong commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +
Please give the actual yaml reference so they can copy

```yaml
// config/packages/shopware.yaml
shopware:
    media:
        remote_thumbnails:
             enable: true,
             pattern: {mediaUrl}/{mediaPath}?width={width}&ts={mediaUpdatedAt}
```

2024-07-01 03:14 UTC, vienthuong commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +To use remote thumbnails, you need to adjust the following parameters in your `shopware.yaml`:
```suggestion
To use remote thumbnails, you need to adjust the following parameters in your `config/packages/shopware.yaml`:
```

2024-07-02 03:43 UTC, vienthuong approved these changes

2024-07-02 03:47 UTC, vienthuong commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +
::: note
This feature is available since Shopware 6.6.4.0
:::

2024-07-02 12:24 UTC, Isengo1989 commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +media:
@tamvt can you add the shopware key here as well. Many people just copy the code.

2024-07-03 06:44 UTC, Isengo1989 approved these changes
Thank you for the PR @tamvt :tada:

2024-07-03 06:49 UTC, Isengo1989 requested changes

2024-07-03 06:49 UTC, Isengo1989 commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +* `mediaPath`: The path of the media file relative to the `mediaUrl`.
```suggestion
* `mediaPath`: The media file path relative to the `mediaUrl`.
```

2024-07-03 06:49 UTC, Isengo1989 commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +1. `shopware.media.remote_thumbnails.enable`: Set this parameter to `true` to enable the use of remote thumbnails.
```suggestion
1. `shopware.media.remote_thumbnails.enable`: Set this parameter to `true` to enable remote thumbnails.
```

2024-07-03 06:49 UTC, Isengo1989 commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +For example, by default the pattern was set as `{mediaUrl}/{mediaPath}?width={width}&ts={mediaUpdatedAt}`, the thumbnail URL would be generated as `https://yourshop.example/abc/123/456.jpg?width=80&t
```suggestion
For example, by default, the pattern was set as `{mediaUrl}/{mediaPath}?width={width}&ts={mediaUpdatedAt}`, the thumbnail URL would be generated as `https://yourshop.example/abc/123/456.jpg?width=80&ts=1718954838`.
```

2024-07-03 06:49 UTC, Isengo1989 commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +Once the configuration is set, Shopware will automatically use the defined pattern to generate URLs for thumbnails.
```suggestion
Once the configuration is set, Shopware will automatically use the defined pattern to generate thumbnail URLs.
```

2024-07-03 06:49 UTC, Isengo1989 commented on guides/plugins/plugins/content/media/remote-thumbnail-generation.md
> +These URLs will point to the external CDN service, which should handle the actual generation and delivery of the thumbnail images.
```suggestion
These URLs will point to the external CDN service, which should handle generating and delivering the thumbnail images.
```

2024-07-03 06:55 UTC, merged