NEXT-37040: Subscription documentation
shopware/docs pull request #1433
Opened 2024-07-10 13:02 UTC by Bird87ZA

2024-07-10 13:43 UTC, mstegmeyer commented on products/extensions/subscriptions/guides/request-scoping.md
> +        <condition>service('license').check('SUBSCRIPTIONS-2437281')</condition>
maybe remove, not necessary for extensions

2024-07-10 13:54 UTC, Bird87ZA commented on products/extensions/subscriptions/guides/index.md
> +This section will help with common topics regarding usage of subscriptions.
I've had a look at the other guides, and they are also one liners. I think the links added to these pages are generated by whatever is presenting it.

2024-07-10 14:18 UTC, lernhart requested changes

2024-07-10 14:18 UTC, lernhart commented on products/extensions/subscriptions/concept.md
> +A plan is a set of rules that define the subscription. This includes the price, the billing interval, and the product that the customer will receive. Plans can be created and managed in the Shopware
A plan may have multiple intervals assigned

2024-07-10 14:19 UTC, lernhart commented
@mstegmeyer do you think we should document the interval logic (relative, absolute, cron stuff, etc.) ?

2024-07-10 14:48 UTC, Bird87ZA commented
> @mstegmeyer do you think we should document the interval logic (relative, absolute, cron stuff, etc.) ?

I think it's a good idea. I shall do it.

2024-07-11 13:03 UTC, mstegmeyer commented on products/extensions/subscriptions/concept.md
> +An absolute interval is an interval that is determined by a fixed date. For example, if a customer subscribes to a monthly plan, the next interval will be on the same day of the month as the first de
No, that's relative again, it's **_relative_** to the start date of the subscription. Absolut would be "the first of the month" or "Every Wednesday"

2024-07-11 13:03 UTC, mstegmeyer commented on products/extensions/subscriptions/guides/request-scoping.md
> +When you are in a subscription checkout, you are using a separate cart and context. In Storefront, there is an additional URL parameter (`subscriptionToken`) that gets resolved. In headless, there ar
The parameters with a `_` are not in the header, but are `attributes` of the request. They tell the resolvers to replace the object with the subscription ones.

2024-07-11 13:03 UTC, mstegmeyer commented on products/extensions/subscriptions/guides/request-scoping.md
> +    -H '_subscriptionContext: true' /
don't think this is necessary

2024-07-11 13:03 UTC, mstegmeyer commented on products/extensions/subscriptions/guides/template-scoping.md
> +} %}
I think, a closing ``` is missing here ;)

2024-07-11 13:13 UTC, mstegmeyer approved these changes

2024-07-15 08:02 UTC, merged

2024-07-15 08:24 UTC, Isengo1989 commented
Thanks for your PR @Bird87ZA :tada: