NEXT-12619 - add data to cms element
shopware/docs pull request #144
Opened 2021-03-15 08:29 UTC by raknison

What should be done?
Create a new article on our GitBook instance which explains how to add custom data to CMS elements. Especially via a dataresolver.
This article should mention:
The prerequisite, a working plugin (Refer to the plugin base guide)
Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
A short code example, including an explanation, on how to do it
Explain it by using a dataresolver
Category: Extensions > Plugins > Content > CMS

2021-03-16 08:21 UTC, lernhart requested changes

2021-03-16 08:21 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +This guide will also not explain how create custom CMS elements in general, so head over to
```suggestion
This guide will not explain how create custom CMS elements in general, so head over to
```

2021-03-16 08:21 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +So as you will now notice, this resolver is called every time for an element of the type `dailymotion`.
```suggestion
This resolver is called every time for an element of the type `dailymotion`.
```

2021-03-16 08:21 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +To register our custom resolver we have to register it as service in the `services.xml` file in our plugin.
```suggestion
To register our custom resolver to the service container we have to register it in the `services.xml` file in our plugin. 
```

2021-03-16 08:21 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +If a `mediaId` exists create a new `CriteriaCollection()` for in. Now we are able to use this media-object later on.
```suggestion
If a `mediaId` exists, we create a new `CriteriaCollection()` for it. Now we are able to use this media-object later on.
```

2021-03-16 08:21 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +Inside the `enrich` you can perform additional logic on the data that has been resolved. Like in the collect data example we have access to our configuration fields
```suggestion
Inside the `enrich` you can perform additional logic on the data that has been resolved. Like in the `collect` method, we have access to our configuration fields
```

2021-03-16 08:21 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +and their values. Imagine you have stored some information in the element configuration and want to perform an external `Api` call to fetch some addition data.
```suggestion
and their values. Imagine you have stored some information in the element configuration and want to perform an external `Api` call to fetch some additional data.
```

2021-03-17 10:56 UTC, PaddyS requested changes

2021-03-17 10:56 UTC, PaddyS commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +This guide will not explain how create custom CMS elements in general, so head over to
```suggestion
This guide will not explain how to create custom CMS elements in general, so head over to
```

2021-03-19 09:52 UTC, lernhart requested changes

2021-03-19 09:52 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +Our custom resolver extends from the `AbstractCmsElementResolver`  which forces us to implement the methods `getType`, `collect` and `enrich`.
```suggestion
Our custom resolver extends from the `AbstractCmsElementResolver` which forces us to implement the methods `getType`, `collect` and `enrich`.
```

2021-03-19 09:52 UTC, lernhart commented on guides/plugins/plugins/content/cms/add-data-to-cms-elements.md
> +If a `mediaId` exists, we create a new `CriteriaCollection()` for it. Now we are able to use this media-object later on.
```suggestion
If a `mediaId` exists, we create a new `CriteriaCollection` for it. Now we are able to use this media-object later on.
```

2021-03-24 13:43 UTC, merged