NEXT-12717 - Add guide on using assets storefront
shopware/docs pull request #147
Opened 2021-03-15 15:22 UTC by leichteckig

2021-03-15 15:53 UTC, leichteckig commented on guides/plugins/themes/add-assets-to-theme.md
> +<img src="{{ asset('themes/your-image.png') }}">
Is that really correct?

2021-03-17 08:04 UTC, raknison approved these changes

2021-03-17 10:59 UTC, PaddyS requested changes

2021-03-17 10:59 UTC, PaddyS commented on guides/plugins/plugins/storefront/add-custom-assets.md
> +possible to add und use custom assets in your Shopware plugin.
```suggestion
possible to add and use custom assets in your Shopware plugin.
```

2021-03-18 10:57 UTC, merged