Adhoc/sales agent docs
shopware/docs pull request #1494
Opened 2024-09-23 12:50 UTC by Isengo1989

Add sales agent to docs

2024-09-30 15:01 UTC, sushmangupta requested changes

2024-09-30 15:01 UTC, sushmangupta commented on products/sales-agent/users.md
> +If you want to restrict the user so that they can only see specific customers, you can send a POST request to the `/api/entity-restriction` endpoint.
```suggestion
To restrict a user to viewing only specific customers, you can send a `POST` request to the `/api/entity-restriction` endpoint.
```

2024-10-01 06:54 UTC, Isengo1989 commented on products/sales-agent/installation.md
> +You can also replace localhost with any IP address or domain name, for example, if you want to test this application from different devices over your local network.
If you want to ..... then change localhost with IP or domain.

2024-10-01 07:00 UTC, lukasrump approved these changes

2024-10-01 07:45 UTC, merged