Explain new twig changes while keeping appropriate warnings
shopware/docs pull request #1500
Opened 2024-10-05 07:54 UTC by JoshuaBehrens

I added new Twig stuff in this [pull request.](https://github.com/shopware/shopware/issues/4980) These are the docs for it.

2024-12-18 13:06 UTC, Isengo1989 commented
Follow up PR currently planned for 6.7 - https://github.com/shopware/shopware/pull/5869

Milestone added but needs to be adjusted if version changes @BrocksiNet

2025-02-11 07:27 UTC, BrocksiNet commented on resources/references/storefront-reference/twig-function-reference.md
> +Official support for complete Twig multi inheritance using sw_* equivalents available since 6.6.7.0
We need to update this version number here to 6.7 ;-)

2025-02-11 10:37 UTC, Isengo1989 requested changes

2025-02-11 10:37 UTC, Isengo1989 commented on resources/references/storefront-reference/twig-function-reference.md
> +Official support for complete Twig multi inheritance using sw_* equivalents available since 6.6.7.0
```suggestion
Official support for complete Twig multi inheritance using sw_* equivalents available since 6.7
```

2025-02-12 14:13 UTC, JoshuaBehrens commented
Everything else is fine? Then I just bump the versions :)

2025-02-12 15:10 UTC, Isengo1989 commented
> Everything else is fine? Then I just bump the versions :)

From DX perspective, yes :+1: 

We might just change the target branch to next-6.7

Anything else @BrocksiNet  from the technical side?

2025-03-27 15:12 UTC, mitelg commented
what is the status here? as the first RC is already released, this should be part of the 6.7 docs :grimacing:

2025-04-09 09:39 UTC, Isengo1989 approved these changes
Thx for the PR @JoshuaBehrens :100: 

LGTM :+1:

2025-04-09 09:42 UTC, merged

2025-04-09 11:43 UTC, JoshuaBehrens commented
Thank you for merging :)