feat: Improve plugin configuration article and add missing settings
shopware/docs pull request #1524
Opened 2024-10-21 09:55 UTC by mitelg

The article about the plugin configuration was a bit outdated. I added missing configs and updated some parts

2024-10-21 09:59 UTC, Fr34k9 commented on guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md
> +You can add the `<requied>` setting to any of your `<input-field>` elements to disable it.
Typo

2024-10-21 12:18 UTC, AydinHassan requested changes

2024-10-21 12:18 UTC, AydinHassan commented on guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md
> +All you need to do is creating a `config.xml` file inside a `Resources/config` directory in your plugin root.
```suggestion
All you need to do is create a `config.xml` file inside a `Resources/config` directory in your plugin root.
```

2024-10-21 12:18 UTC, AydinHassan commented on guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md
> +Unless defined otherwise, your `<input-field>` will be a text field per default.
```suggestion
Unless defined otherwise, your `<input-field>` will be a text field.
```

2024-10-21 12:18 UTC, AydinHassan commented on guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md
> +_Please note, `<required>` only takes boolean values._
```suggestion
_Please note, `<required>` only accepts boolean values._
```

2024-10-21 12:18 UTC, AydinHassan commented on guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md
> +Please Note: It is impossible to allow every component to the config.xml, due to their complexities.
```suggestion
Please Note: It is impossible to allow every component in the config.xml, due to their complexities.
```

2024-10-22 07:05 UTC, AydinHassan commented on guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md
> +All you need to do is creating a `config.xml` file inside a `Resources/config` directory in your plugin root.
I am sure, creating is definitely wrong

2024-10-22 07:56 UTC, bojanrajh approved these changes

2024-10-22 07:58 UTC, AydinHassan approved these changes

2024-10-22 07:58 UTC, AydinHassan commented
nice work @mitelg !

2024-10-22 08:02 UTC, merged