Update index.md
shopware/docs pull request #1547
Opened 2024-11-08 09:38 UTC by mboelt

Fixed some LB and typo errors.

2024-11-08 10:03 UTC, mitelg requested changes

2024-11-08 10:03 UTC, mitelg commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +You can no longer advertise your Shopware certificates within the app description, in your app images, or in your manufacturer profile. The manufacturer/partner certificates are dynamically loaded at
```suggestion
You can no longer advertise your Shopware certificates within the app description, in your app images, or in your manufacturer profile.
The manufacturer/partner certificates are dynamically loaded at the end of each app description and published by us.
```

2024-11-08 10:03 UTC, mitelg commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +We differentiate between "Technically required","Marketing" and "Comfort features".
```suggestion
We differentiate between "Technically required", "Marketing" and "Comfort features".
```

2024-11-08 10:03 UTC, mitelg commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +The technical app name must be stored in the first part of composer.json, located at composer.json > extra > shopware-plugin-class.
it does not really matter where this located in the composer.json :thinking:

2024-11-08 10:03 UTC, mitelg commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +Link: [Exampl eof a valid composer.json](https://github.com/FriendsOfShopware/FroshPlatformPerformance/blob/master/composer.json#L20).
```suggestion
Link: [Example of a valid composer.json](https://github.com/FriendsOfShopware/FroshPlatformPerformance/blob/master/composer.json#L20).  
```

2024-11-08 10:03 UTC, mitelg commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +*./tests
```suggestion
* /tests
```

this was just changed by you :thinking:

2024-11-13 12:39 UTC, sushmangupta requested changes

2024-11-13 12:39 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +The technical app name must be stored in the first part of composer.json, located at composer.json > extra > shopware-plugin-class.
```suggestion
The technical app name must be stored in the composer.json, located at `composer.json` > extra > `shopware-plugin-class`.
```

2024-11-13 12:52 UTC, sushmangupta requested changes

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +Link: [Documentation for Extension Partner](https://docs.shopware.com/en/account-en/extension-partner/extensions?category=account-en/extension-partner#how-can-i-request-a-preview)
```suggestion
[Differentiator cluster for Shopware extensions](https://developer.shopware.com/docs/resources/guidelines/testing/Differentiator-Clusters.html)
[Documentation for Extension Partner](https://docs.shopware.com/en/account-en/extension-partner/extensions?category=account-en/extension-partner#how-can-i-request-a-preview)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +Link: [Developer documentation article to add private dependency](../../../../../guides/plugins/plugins/plugin-fundamentals/using-composer-dependencies)
```suggestion
[Developer documentation article to add private dependency](../../../../../guides/plugins/plugins/plugin-fundamentals/using-composer-dependencies)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +Link: [Injecting into the Administration](https://developer.shopware.com/docs/guides/plugins/plugins/administration/add-custom-field.html#injecting-into-the-administration)
```suggestion
[Loading the JS files](https://developer.shopware.com/docs/guides/plugins/plugins/administration/add-custom-field.html#loading-the-js-files)
[Injecting into the Administration](https://developer.shopware.com/docs/guides/plugins/plugins/administration/add-custom-field.html#injecting-into-the-administration)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +  * Link: [Google Lighthouse](https://developers.google.com/web/tools/lighthouse)
```suggestion
  * [Google Lighthouse](https://developers.google.com/web/tools/lighthouse)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +  * Link: [Google Rich Result Tester](https://search.google.com/test/rich-results)
```suggestion
  * [Schema Markup Validator of schema.org](https://validator.schema.org/)
  * [Google Rich Result Tester](https://search.google.com/test/rich-results)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> + * Link: [Github](https://github.com/shyim/ShyimApiTest)
```suggestion
 * [Github](https://github.com/shyim/ShyimApiTest)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +* Link: [Code reviews for Shopware 6 on GitHub](https://github.com/shopwareLabs/store-plugin-codereview)
```suggestion
* [Code reviews for Shopware 6 on GitHub](https://github.com/shopwareLabs/store-plugin-codereview)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +* Link: [Refer to the list of the already existing blockers](https://s3.eu-central-1.amazonaws.com/wiki-assets.shopware.com/1657519735/blocker.txt).
```suggestion
* [Refer to the list of the already existing blockers](https://s3.eu-central-1.amazonaws.com/wiki-assets.shopware.com/1657519735/blocker.txt).
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +* Link: [Cypress Tests for Shopware 6](https://github.com/shopware/shopware/tree/trunk/src/Administration/Resources)
```suggestion
* [Developer Documentation Cypress Tests for Shopware 6](/docs/guides/plugins/plugins/testing/end-to-end-testing)
* [Cypress Tests for Shopware 6](https://github.com/shopware/shopware/tree/trunk/src/Administration/Resources)
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +* Link: [Shopware CLI tools](https://github.com/shopwareLabs/sw-cli-tools): When you think about performance, these are various useful console helpers for generating data.
```suggestion
* [FroshPluginUploader](https://github.com/FriendsOfShopware/FroshPluginUploader): Tool for validating and uploading new SW6 app releases to the Community Store (GitHub Project from "Friends of Shopware")]
* [Shopware CLI tools](https://github.com/shopwareLabs/sw-cli-tools): When you think about performance, these are various useful console helpers for generating data.
```

2024-11-13 12:52 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-plugins/index.md
> +Link: [Example of a valid composer.json](https://github.com/FriendsOfShopware/FroshPlatformPerformance/blob/master/composer.json#L20).
```suggestion
[Example of a valid composer.json](https://github.com/FriendsOfShopware/FroshPlatformPerformance/blob/master/composer.json#L20).  
```

2024-11-13 12:59 UTC, sushmangupta approved these changes

2024-11-13 13:04 UTC, sushmangupta approved these changes

2024-11-13 13:08 UTC, merged