Update storefront modal docs
shopware/docs pull request #1592
Opened 2024-12-04 10:12 UTC by tobiasberge

Docs about modal are slightly outdated in 6.6.

* Update modal DOM structure to be aligned with Bootstrap 5. 
* Fix invalid button without closing element

2024-12-04 13:18 UTC, Phil23 requested changes

2024-12-04 13:43 UTC, tobiasberge commented on guides/plugins/plugins/storefront/using-a-modal-window.md
> +    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
It seems those attributes are added by the modal JavaScript on-the-fly when the modal is opened: https://getbootstrap.com/docs/5.3/components/modal/#live-demo

The attributes are also not part of the Bootstrap HTML example.

2024-12-05 07:44 UTC, Isengo1989 commented on guides/plugins/plugins/storefront/using-a-modal-window.md
> +    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
![image](https://github.com/user-attachments/assets/d316c3d7-0bed-46a9-8d35-fb06a2ebf139)

2024-12-05 07:45 UTC, Isengo1989 approved these changes
Thx for the PR @tobiasberge :tada:

2024-12-05 08:01 UTC, Phil23 approved these changes

2024-12-05 15:41 UTC, merged