docs: speculations rules API javascript plugin
shopware/docs pull request #1607
Opened 2024-12-11 10:48 UTC by BrocksiNet

Add docs about the new experimental javascript plugin.

2024-12-11 13:22 UTC, shyim approved these changes

2024-12-12 08:08 UTC, Isengo1989 requested changes
Thx for the PR @BrocksiNet :tada: 

Added some small suggestions and a short explanation of what the feature does.

2024-12-12 08:08 UTC, Isengo1989 commented on guides/hosting/performance/performance-tweaks.md
> +Keep in mind that pre-rendering is putting extra load on your server and also can affect your [Analytics](https://developer.chrome.com/docs/web-platform/prerender-pages#impact-on-analytics).
```suggestion
Keep in mind that pre-rendering puts extra load on your server and can also affect your [Analytics](https://developer.chrome.com/docs/web-platform/prerender-pages#impact-on-analytics).
```

2024-12-12 08:08 UTC, Isengo1989 commented on guides/hosting/performance/performance-tweaks.md
> +This is available starting with Shopware 6.6.10.0
```suggestion
This feature is available starting with Shopware 6.6.10.0
```

2024-12-12 13:40 UTC, Isengo1989 approved these changes
We will merge it as soon as the version is out. With this PR we are getting informed proactively by a comment as soon as it happens

2024-12-16 10:32 UTC, BrocksiNet commented
Merged here: https://github.com/shopware/shopware/commit/2e7c627cf5a8a2252f3ec61086d29b47aa518812.

2024-12-18 12:55 UTC, merged