NEXT-12688 - Versioning entities
shopware/docs pull request #161
Opened 2021-03-19 14:05 UTC by Dominik28111

2021-03-22 08:47 UTC, lernhart requested changes

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +First of all, we have to a new columns to our table, `version_id` which has to be a primary key beside the `id`.
```suggestion
First of all, we have to add a new column to our table: `version_id` which in union with the `id` field replaces the primary key.
```

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +When we merge a particular version, all versions before the merged version are deleted. The version can
The version can ... ??

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +*Note: If an entity is not loaded in the specified version, the live version is reverted to.*
[...] is reverted to what ? Or is it [...] reverted, too ?

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +public function exampleVersioning(Context $context)
```suggestion
public function exampleVersioning(Context $context): void
```

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +Now we did repository searches with our versioned `Context` and our normal.
```suggestion
Subsequently, we searched the repository with the original context and our new versioned context.
```

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +In the first search result with our normal `Context` we get the first version of our entity that we created at the beginning.
```suggestion
In the first search result, using the original context, we get the first version of our entity, which we created at the beginning.
```

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +The second search result with the updated `Context` w get the updated entity.
```suggestion
With the second search result we get the updated entity, using our new versioned context.
```

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +The merged version is now our new live version. From now on we can find it with the normal `Context`.
```suggestion
The merged version is now our new live version. From now on we can find it without using a versioned context.
```

2021-03-22 08:47 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +In this example we're using an inherited field. If you are not familiar with this, head over to our [Field inheritance](./field-inheritance.md) guide.
```suggestion
If you have an entity with foreign keys, your foreign keys also need to be versioned.
In this example we're using an inherited field. If you are not familiar with inheritance, head over to our [Field inheritance](./field-inheritance.md) guide.
```

2021-03-23 08:57 UTC, lernhart requested changes

2021-03-23 08:57 UTC, lernhart commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +With the second search result we get with the updated entity, using our new versioned context.
```suggestion
With the second search result we get the updated entity, using our new versioned context.
```

2021-03-23 14:58 UTC, JoshuaBehrens commented
Why is `parent_version_id` NULL in SQL but with a Required-flag in DAL?

2021-04-01 13:50 UTC, PaddyS requested changes

2021-04-01 13:50 UTC, PaddyS commented on guides/plugins/plugins/framework/data-handling/versioning-entities.md
> +For this head over to our [Field inheritance](./field-inheritance.md) guide.
Remove

2021-04-01 13:58 UTC, merged