NEXT-12721 - added fetching data with javascript
shopware/docs pull request #166
Opened 2021-03-24 08:22 UTC by raknison

**What should be done?**

Create a new article on our GitBook instance which explains how to fetch data via javascript.
This article should mention:
The prerequisite, a working plugin (Refer to the plugin base guide)
Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
A short code example, including an explanation, on how to do it
Might want to ask Tobias Berge on how to do it, if unclear

Category: Extensions > Plugins > Storefront

2021-03-26 15:26 UTC, leichteckig requested changes

2021-03-26 15:26 UTC, leichteckig commented on guides/plugins/plugins/storefront/fetching-data-with-javascript.md
> +When you develop your own plugin, you might want to fetch data from the API which you need. This guide explains how to `
```suggestion
When you develop your own plugin, you might want to fetch necessary data from the API. This guide explains how to 
```

2021-03-26 15:26 UTC, leichteckig commented on guides/plugins/plugins/storefront/fetching-data-with-javascript.md
> +{% page-ref page="./add-custom-javascript.md" %}
These `page-ref` links might still be broken, like in my guides. 🙈  I would leave it in here, but we should keep in mind that we might to fix them later.

2021-03-26 15:26 UTC, leichteckig commented on guides/plugins/plugins/storefront/fetching-data-with-javascript.md
> +The `get` method take three arguments. The first one is the `url` which we want to call. In the example we are going
```suggestion
The `get` method takes three arguments. The first one is the `url` which we want to call. In the example we are going 
```

2021-03-30 07:50 UTC, tobiasberge approved these changes

2021-03-30 08:09 UTC, leichteckig approved these changes

2021-03-30 08:10 UTC, merged