NEXT-12691 - Add message to queue
shopware/docs pull request #174
Opened 2021-03-29 07:35 UTC by Dominik28111

2021-03-29 09:39 UTC, lernhart requested changes

2021-03-29 09:39 UTC, lernhart commented on guides/plugins/plugins/framework/message-queue/add-message-to-queue.md
> +A [message](https://symfony.com/doc/current/messenger.html#creating-a-message-handler) is a simple PHP class that you want to dispatch over the MessageQueue.
I'd prefer the terminology `object`.

```suggestion
A [message](https://symfony.com/doc/current/messenger.html#creating-a-message-handler) is a simple PHP object that you want to dispatch over the MessageQueue. 
```

2021-03-29 09:39 UTC, lernhart commented on guides/plugins/plugins/framework/message-queue/add-message-to-queue.md
> +## Overview
I'm missing a general explanation, what a the message queue is. 

The message queue allows you to ... 

Maybe you can copy something from the symfony docs as some sort of introduction here

2021-03-29 09:39 UTC, lernhart commented on guides/plugins/plugins/framework/message-queue/add-message-to-queue.md
> +If we want to add metadata to our message, we can simply dispatch an `Symfony\Component\Messenger\Envelope` with the necessary
```suggestion
If we want to add metadata to our message, we can dispatch an `Symfony\Component\Messenger\Envelope` in our Service instead with the necessary 
```

2021-03-29 09:39 UTC, lernhart commented on guides/plugins/plugins/framework/message-queue/add-message-to-queue.md
> +    );
```suggestion
    $this->bus->dispatch(
        (new Envelope($message))
            ->with(new DelayStamp(5000))
    );
```

2021-03-30 09:24 UTC, lernhart approved these changes

2021-03-31 09:52 UTC, PaddyS requested changes
Dead links

2021-04-01 09:51 UTC, merged