NEXT-12776 -  [MIGRATE] Administration: Using mixins
shopware/docs pull request #175
Opened 2021-03-29 12:05 UTC by NiklasLimberg

## What should be done?

Create a new article on our [GitBook instance|https://app.gitbook.com/@shopware/s/shopware/] which explains how to use mixins in the administration.
This can be migrated from our previous documentation.

This article should mention:
- The prerequisite, a working plugin (Refer to the plugin base guide)
- Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
- A short code example, including an explanation, on how to do it

Category: Extensions > Plugins > Administration

## Are there already guides in the previous documentation for this?
Yes! But please, don't just copy & paste. Make sure it still works and rewrite it to fit our new [writing guidelines|https://app.gitbook.com/@shopware/s/shopware/resources/guidelines/documentation/writing]!
- Search for "Mixins": https://docs.shopware.com/en/shopware-platform-dev-en/how-to/custom-cms-element

For more information, ask me, [~p.stahl].

2021-03-29 12:25 UTC, leichteckig requested changes

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/add-mixins.md
>  This documentation chapter will cover how to add a new administration Mixin for your plugin.
```suggestion
This documentation chapter will cover how to add a new administration mixin for your plugin.
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/add-mixins.md
>  Generally, mixins behave the same as they do in Vue normally, differing only in the registration and the way mixins are included in a component.
```suggestion
In general, mixins behave the same as they do in Vue normally, differing only in the registration and the way mixins are included in a component.
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +## Finding a Mixin
```suggestion
## Finding a mixin
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +| Mixin                       | Description                                                                                                                                 | Link
Wouldn't that fit better as a reference page? Even if it's a small one :)

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +| discard-detail-page-changes | Mixin which resets entity changes on page leave or if the id of the entity changes. This also affects changes in associations of the entity | [link](https://github.com
Mixin names in code syntax please, e.g.:


```suggestion
| `discard-detail-page-changes` | Mixin which resets entity changes on page leave or if the id of the entity changes. This also affects changes in associations of the entity | [link](https://github.com/shopware/platform/blob/v6.3.5.1/src/Administration/Resources/app/administration/src/app/mixin/discard-detail-page-changes.mixin.js) |
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +| listing                     | Mixin wich is used in almost all listing pages to for example keep track of the current page of the administration                          | [link](https://github.com
```suggestion
| listing                     | Mixin which is used in almost all listing pages to for example keep track of the current page of the administration                          | [link](https://github.com/shopware/platform/blob/v6.3.5.1/src/Administration/Resources/app/administration/src/app/mixin/listing.mixin.js)                     |
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +| notification                | This mixin is used to easier create notifications in the administrations                                                                    | [link](https://github.com
```suggestion
| notification                | This mixin is used to create notifications in the administrations more easily                                                                   | [link](https://github.com/shopware/platform/blob/v6.3.5.1/src/Administration/Resources/app/administration/src/app/mixin/notification.mixin.js)                |
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +| remove-api-error            | This mixin removes API errors after the user for example corrected a invalid input i.e. leaving the product name field blank                | [link](https://github.com
```suggestion
| remove-api-error            | This mixin removes API errors e.g. after the user corrected a invalid input i.e. leaving the product name field blank                | [link](https://github.com/shopware/platform/blob/v6.3.5.1/src/Administration/Resources/app/administration/src/app/mixin/remove-api-error.mixin.js)            |
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +After we've found the mixin we need.
```suggestion
After we've found the mixin we need,
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +We can get it from the registry with the `Mixin.getByName` function and inject it into our component as seen below.
```suggestion
we can get it from the registry with the `Mixin.getByName` function and inject it into our component as seen below.
```

2021-03-29 12:25 UTC, leichteckig commented on guides/plugins/plugins/administration/using-mixins.md
> +If you however want to add your own service to the administration:
```suggestion
However, if you want to add your own service to the administration take a look at this guide:
```

2021-03-30 07:02 UTC, lernhart requested changes

2021-03-30 07:02 UTC, lernhart commented on guides/plugins/plugins/administration/using-mixins.md
> +        greet: function (){
```suggestion
        greet: function () {
```

2021-03-30 07:02 UTC, lernhart commented on guides/plugins/plugins/administration/using-mixins.md
> +Now that you learned how to use a mixin, you might want to create or customize an administration component or create your own mixn:
```suggestion
Now that you learned how to use a mixin, you might want to create or customize an administration component or create your own mixin:
```

2021-03-30 07:02 UTC, lernhart commented on guides/plugins/plugins/administration/using-mixins.md
> +* [Creating a Mixin](./add-mixins.md)
```suggestion
* [Creating a mixin](./add-mixins.md)
```

2021-03-30 07:02 UTC, lernhart commented on guides/plugins/plugins/administration/using-mixins.md
> +If you want to learn how to create your own mixn look at this guide: [Creating Mixins](./add-mixins.md)
```suggestion
If you want to learn how to create your own mixn look at this guide: [Creating mixins](./add-mixins.md)
```

2021-03-30 07:02 UTC, lernhart commented on resources/references/core-reference/administration-reference/mixins.md
> +Mixins in the Shopware 6 Administration, are essentially the same as normally in Vue.
```suggestion
Mixins in the Shopware 6 Administration are essentially the same in default Vue.
```

2021-03-30 07:02 UTC, lernhart commented on resources/references/core-reference/administration-reference/mixins.md
> +or if you want to register your own take a look at this [guide](./../../../../guides/plugins/plugins/administration/add-mixins.md)
```suggestion
or if you want to register your own mixin take a look at this [guide](./../../../../guides/plugins/plugins/administration/add-mixins.md)
```

2021-03-30 07:03 UTC, lernhart commented on resources/references/core-reference/administration-reference/mixins.md
> +## Overview of all the mixins
Please order the table descending by mixin name A-Z

2021-03-30 08:23 UTC, leichteckig requested changes

2021-03-30 08:23 UTC, leichteckig commented on resources/references/core-reference/administration-reference/mixins.md
> +If u want to learn how to use them in your plugin, take a look at this guide [here](./../../../../guides/plugins/plugins/administration/using-mixins.md)
I like it informal, but I assume we aren't allowed to use that in our docs. ;)

```suggestion
If you want to learn how to use them in your plugin, take a look at this guide [here](./../../../../guides/plugins/plugins/administration/using-mixins.md)
```

2021-03-30 08:23 UTC, leichteckig commented on guides/plugins/plugins/administration/add-mixins.md
> +This can also be done with Shopware provided mixins learn more about them here: [Using Mixins](./using-mixins.md)
```suggestion
This can also be done with Shopware provided mixins, learn more about them here: [Using Mixins](./using-mixins.md)
```

2021-03-31 14:29 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/using-mixins.md
> +In this example we'll use the notification mixin.
i can't think of anything better so i guess i'll apply this

2021-04-06 05:28 UTC, raknison approved these changes

2021-04-06 08:11 UTC, leichteckig approved these changes

2021-04-07 12:28 UTC, PaddyS commented
@NiklasLimberg Rebase > Merge

2021-04-08 06:51 UTC, merged