NEXT-12692 - Add message handler
shopware/docs pull request #176
Opened 2021-03-29 13:45 UTC by Dominik28111

2021-03-30 13:08 UTC, lernhart requested changes

2021-03-31 12:26 UTC, PaddyS requested changes

2021-03-31 12:26 UTC, PaddyS commented on guides/plugins/plugins/framework/message-queue/add-message-handler.md
> +There is also an API-Route that let you consume messages for a given transport.
```suggestion
There is also an API-Route that lets you consume messages for a given transport.
```

2021-03-31 12:26 UTC, PaddyS commented on guides/plugins/plugins/framework/message-queue/add-message-handler.md
> +### Adminer worker
```suggestion
### Admin worker
```

2021-04-01 10:12 UTC, merged