NEXT-12693 - Add middleware
shopware/docs pull request #177
Opened 2021-03-30 08:18 UTC by Dominik28111

2021-03-30 13:12 UTC, lernhart requested changes

2021-03-30 13:12 UTC, lernhart commented on guides/plugins/plugins/framework/message-queue/add-middleware.md
> +## Prerequisites
Add a prerequisite to your other message queue guides

2021-03-31 12:27 UTC, PaddyS requested changes

2021-03-31 12:27 UTC, PaddyS commented on guides/plugins/plugins/framework/message-queue/add-middleware.md
> +{% endcode %}
Might want to add:
```
## More interesting topics

* [Message Queue](...)
* [Message Handler](...)
```

2021-04-01 11:25 UTC, merged