NEXT-12787 - [NEW] Administration: Add middleware to existing service
shopware/docs pull request #181
Opened 2021-03-31 07:05 UTC by NiklasLimberg

## What should be done?

Create a new article on our [GitBook instance|https://app.gitbook.com/@shopware/s/shopware/] which explains how to add middleware to existing services and factories.

This article should mention:
- The prerequisite, a working plugin (Refer to the plugin base guide)
- Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
- A short code example, including an explanation, on how to do it
- Ask Jannis if unclear

Category: Extensions > Plugins > Administration

## Are there already guides in the previous documentation for this?
Unfortunately, No. But please have a look at our [example guide|https://app.gitbook.com/@shopware/s/shopware/guides/plugins/plugins/plugin-base-guide](e.g. note the PLACEHOLDERs for cross-references, that do not exist yet) and the [Writing guidelines|https://app.gitbook.com/@shopware/s/shopware/resources/guidelines/documentation/writing].

For more information, ask me, [~p.stahl].

2021-03-31 12:30 UTC, PaddyS approved these changes

2021-04-06 06:58 UTC, jleifeld commented
I would also add documentation about `resetProviders` :)

2021-04-07 12:30 UTC, PaddyS requested changes

2021-04-07 12:30 UTC, PaddyS commented on guides/plugins/plugins/administration/add-custom-service.md
> +Another useful BottleJS is the [`resetProviders`](https://github.com/young-steveo/bottlejs#resetprovidersnames) function.
"Another useful BottleJS" what?
Function? Technique? Feature? There's on word missing

2021-04-07 12:30 UTC, PaddyS commented on guides/plugins/plugins/administration/add-custom-service.md
> +If names param is passed, will reset only the named providers.
```suggestion
If the `names` param is passed, it will reset only the named providers.
```

2021-04-08 06:27 UTC, jleifeld commented on guides/plugins/plugins/administration/add-custom-service.md
> +```
I would also add a practical example where you add middleware afterwards to existing services from the core

2021-04-08 11:35 UTC, leichteckig requested changes

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/add-custom-service.md
Do we need an `h1` here?

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/add-custom-service.md
> +For this we need to change our previously used service, like this:
```suggestion
For this we need to change our previously used service, as seen below: 
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +This guide will teach you how to extend a Shopware provided service, with middleware and decorators.
```suggestion
This guide will teach you how to extend a Shopware provided service with middleware and decorators.
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +You need to do this to add decorators or middleware to shopware provided services after they are initially instantiated in the Shopware boot-process.
```suggestion
You need to do this to add decorators or middleware to Shopware provided services, after they are initially instantiated in the Shopware boot-process.
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +If the `names` param is passed, it will reset only the named providers.
```suggestion
If the `names` param is passed, it will only reset the named providers.
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +The function should return the service, or another object to be used as the service instead.
```suggestion
The function should return the service or another object to be used as the service instead.
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +With Shopware you have to reset the providers, before extending Service.
```suggestion
With Shopware you have to reset the providers before extending Service.
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +Let's look at an Example:
```suggestion
Let's look at an example:
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +[BottleJS middleware](https://github.com/young-steveo/bottlejs#middleware) are similar to decorators, but they are executed every time a service is accessed from the container.
```suggestion
[BottleJS middleware](https://github.com/young-steveo/bottlejs#middleware) is similar to decorators, but they are executed every time a service is accessed from the container.
```

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +They are passed the service instance and a next function:
Maybe:

```suggestion
They are passing the service instance and a next function:
```

I had trouble understanding this sentence correctly. What was your intention in it??

2021-04-08 11:35 UTC, leichteckig commented on guides/plugins/plugins/administration/extending-services.md
> +
Remove one of the empty lines pls.

2021-04-08 11:45 UTC, PaddyS commented on guides/plugins/plugins/administration/add-custom-service.md
There is - just hidden. :-D

2021-04-08 11:47 UTC, leichteckig commented on guides/plugins/plugins/administration/add-custom-service.md
Ah nvm then :D

2021-04-08 11:48 UTC, PaddyS commented
@leichteckig 's comments are sufficient. Approve if they are done

2021-04-08 12:24 UTC, jleifeld approved these changes

2021-04-08 13:04 UTC, leichteckig requested changes
My threads aren't resolved yet.

2021-04-08 13:36 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/extending-services.md
> +
```suggestion
```

2021-04-08 13:55 UTC, leichteckig approved these changes

2021-04-09 11:57 UTC, merged