Ntr/some more polishing
shopware/docs pull request #187
Opened 2021-03-31 14:55 UTC by leichteckig

2021-04-01 13:35 UTC, PaddyS requested changes

2021-04-01 13:35 UTC, PaddyS commented on guides/hosting/performance/caches.md
> +The HTTP Cache is a *must have_ for every production system. With enabled cache the performance of the shop can be greatly increased.
`*must*` ?

2021-04-01 13:35 UTC, PaddyS commented on guides/integrations-api/admin-api/action-routes.md
> +## ACtion Routes
```suggestion
## Action Routes
```

2021-04-01 13:35 UTC, PaddyS commented on guides/plugins/apps/administration/add-custom-module.md
> +if the user opens the module in the administration your app will receive a request to the given source url. Your app can determine the shop that has opened the module through query parameters added t
```suggestion
If the user opens the module in the administration your app will receive a request to the given source url. Your app can determine the shop that has opened the module through query parameters added to the url: 
```

2021-04-06 12:17 UTC, raknison approved these changes

2021-04-06 12:20 UTC, merged