NEXT-12784 - [NEW] Administration: Add data sanitizing
shopware/docs pull request #195
Opened 2021-04-01 13:56 UTC by NiklasLimberg

## What should be done?

Create a new article on our [GitBook instance|https://app.gitbook.com/@shopware/s/shopware/] which explains how to add data sanitizing in the administration.

This article should mention:
- The prerequisite, a working plugin (Refer to the plugin base guide)
- Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
- A short code example, including an explanation, on how to do it

Category: Extensions > Plugins > Administration

## Are there already guides in the previous documentation for this?
Unfortunately, No. But please have a look at our [example guide|https://app.gitbook.com/@shopware/s/shopware/guides/plugins/plugins/plugin-base-guide](e.g. note the PLACEHOLDERs for cross-references, that do not exist yet) and the [Writing guidelines|https://app.gitbook.com/@shopware/s/shopware/resources/guidelines/documentation/writing].

For more information, ask me, [~p.stahl].

2021-04-01 13:59 UTC, leichteckig requested changes

2021-04-01 13:59 UTC, leichteckig commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +The Shopware 6 Sanitizer Helper is a wrapper around [`DOMPurify`](https://github.com/cure53/DOMPurify), wich is used to sanitize HTML in order to prevent `XSS attacks`.
Do we need some prerequisites here?

2021-04-01 13:59 UTC, leichteckig commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +this.$sanitizer.sanitize('<svg><g/onload=alert(2)//<p>'); // becomes <svg><g></g></svg>
I like! 👍

2021-04-06 09:36 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +The Shopware 6 Sanitizer Helper is a wrapper around [`DOMPurify`](https://github.com/cure53/DOMPurify), wich is used to sanitize HTML in order to prevent `XSS attacks`.
Probably not

2021-04-06 12:03 UTC, leichteckig requested changes

2021-04-06 12:03 UTC, leichteckig commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +As mentioned before the SanitizerHelper is registered to the [Shopware Global Object](./the-shopware-object.md) and therefore can be accessed like this everywhere:
```suggestion
As mentioned before the `SanitizerHelper` is registered to the [Shopware Global Object](./the-shopware-object.md) and therefore can be accessed like this everywhere:
```

2021-04-06 12:03 UTC, leichteckig commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +The config can be set with the and deleted with the function, as seen below:
I'm not sure I understand this sentence. Maybe it's missing a word or there are too many? 🤔 
Probably: 

```suggestion
The config can be set deleted with the function, as seen below:
```

2021-04-07 09:53 UTC, PaddyS requested changes

2021-04-07 12:04 UTC, leichteckig requested changes
Just 2 more things, then it's an approve! 👍

2021-04-07 12:04 UTC, leichteckig commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +## How to add Hooks
```suggestion
## How to add hooks
```

2021-04-07 12:04 UTC, leichteckig commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +# The Sanitizer Helper
```suggestion
# The Sanitizer helper
```

2021-04-07 12:23 UTC, leichteckig approved these changes

2021-04-07 12:29 UTC, raknison requested changes

2021-04-07 12:29 UTC, raknison commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +const sanatizer = Shopware.Helper.SanitizerHelper;
```suggestion
const sanitizer = Shopware.Helper.SanitizerHelper; 
```

2021-04-07 12:29 UTC, raknison commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +The Sanitizer Helper is registered to the [Shopware Global Object](./the-shopware-object.md) and therefore can be accessed anywhere in your Plugin.
```suggestion
The Sanitizer Helper is registered to the [Shopware Global Object](./the-shopware-object.md) and therefore can be accessed anywhere in your plugin.
```

2021-04-07 12:29 UTC, raknison commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +const Sanitizer = this.$sanitizer;
```suggestion
const sanitizer = this.$sanitizer;
```

why did you capitalise `Sanitizer`

2021-04-08 06:33 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/the-sanitizer-helper.md
> +const Sanitizer = this.$sanitizer;
Its a class. Well not really but kindof

2021-04-08 08:51 UTC, raknison approved these changes

2021-04-09 11:58 UTC, merged