NEXT-12786 - [NEW] Administration: Add error-handling
shopware/docs pull request #216
Opened 2021-04-13 13:06 UTC by NiklasLimberg

## What should be done?

Create a new article on our [GitBook instance|https://app.gitbook.com/@shopware/s/shopware/] which explains how to add proper error-handling in the administration.

This article should mention:
- The prerequisite, a working plugin (Refer to the plugin base guide)
- Every other prerequisite you figure out during writing the guide (e.g. a subscriber, knowing how to create a service, a controller, etc.)
- A short code example, including an explanation, on how to do it

Category: Extensions > Plugins > Administration

## Are there already guides in the previous documentation for this?
Unfortunately, No. But please have a look at our [example guide|https://app.gitbook.com/@shopware/s/shopware/guides/plugins/plugins/plugin-base-guide](e.g. note the PLACEHOLDERs for cross-references, that do not exist yet) and the [Writing guidelines|https://app.gitbook.com/@shopware/s/shopware/resources/guidelines/documentation/writing].

For more information, ask me, [~p.stahl].

2021-04-14 09:04 UTC, jleifeld requested changes

2021-04-14 09:04 UTC, jleifeld commented on guides/plugins/plugins/administration/add-error-handling.md
> +Wich then are bound to the inputs like this:
Which

2021-04-14 09:06 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +Wich then are bound to the inputs like this:
```suggestion
Which then are bound to the inputs like this:
```

2021-04-14 09:08 UTC, jleifeld approved these changes

2021-04-14 09:22 UTC, raknison commented on guides/plugins/plugins/administration/add-error-handling.md
> +# API error handling in administration)
```suggestion
# API error handling in administration
```

2021-04-14 09:44 UTC, raknison commented on guides/plugins/plugins/administration/add-error-handling.md
> +Component.register('sw-product-basic-form', {
something is weird here - triple `register` ?

2021-04-14 10:51 UTC, raknison requested changes

2021-04-14 11:14 UTC, leichteckig requested changes

2021-04-14 11:14 UTC, leichteckig commented on guides/plugins/plugins/administration/add-error-handling.md
> +When working with nested views you need a way to tell the user that an error occurred on another view, e.g tab.
```suggestion
When working with nested views, you need a way to tell the user that an error occurred on another view, e.g in another `tab`.
```

2021-04-14 11:14 UTC, leichteckig commented on guides/plugins/plugins/administration/add-error-handling.md
> +For this you can write a config for your `sw-page` component which looks like:
```suggestion
For this you can write a config for your `sw-page` component which looks like seen below: 
```

2021-04-14 11:14 UTC, leichteckig commented on guides/plugins/plugins/administration/add-error-handling.md
> +Wich then makes it possible to indicate if one or more errors exists, in another view or a tab:
```suggestion
This makes it possible to indicate if one or more errors exists, in another view or a tab:
```

2021-04-14 11:38 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +Where they are centrally accessible to your components, with a flat data structure wich looks like this:
I meant the Vuex store

2021-04-14 11:39 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +​
```suggestion
```

2021-04-14 11:40 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +Component.register('sw-product-basic-form', {
```suggestion
Component.register('sw-product-basic-form', {
```

2021-04-14 12:11 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +<sw-field type="text" v-model="product.name" :error="productNameError"
```suggestion
<sw-field type="text" v-model="product.name" :error="productNameError">
```

2021-04-14 12:11 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +<sw-field type="text" v-model="product.name" :error="productNameError"
```suggestion
<sw-field type="text" v-model="product.name" :error="productNameError">
```

2021-04-14 12:12 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +Which then are bound to the inputs like this:
it was the missing end tag

2021-04-14 12:20 UTC, leichteckig requested changes

2021-04-14 12:20 UTC, leichteckig commented on guides/plugins/plugins/administration/add-error-handling.md
> +Which then are bound to the inputs like this:
Ah perfect - good catch 👍

2021-04-14 12:20 UTC, leichteckig commented on guides/plugins/plugins/administration/add-error-handling.md
> +Where they are centrally accessible to your components, with a flat data structure wich looks like this:
Ok, in this case the suggestion is valid 👍

2021-04-14 12:26 UTC, NiklasLimberg commented on guides/plugins/plugins/administration/add-error-handling.md
> +Where they are centrally accessible to your components, with a flat data structure wich looks like this:
i modifed the sugestion a bit are u fine with this?

2021-04-14 12:47 UTC, leichteckig approved these changes

2021-04-14 13:56 UTC, elkmod commented
Please add entry to SUMMARY.md.

2021-04-15 09:07 UTC, leichteckig requested changes
See comment concerning `SUMMARY.md`

2021-04-16 08:09 UTC, leichteckig approved these changes

2021-04-20 06:00 UTC, raknison approved these changes

2021-04-20 06:02 UTC, merged