NEXT-15111 - Added concept parts for data abstraction layer
shopware/docs pull request #267
Opened 2021-05-11 06:29 UTC by OliverSkroblin

2021-05-11 11:44 UTC, PaddyS requested changes

2021-05-11 11:44 UTC, PaddyS commented on concepts/framework/data-abstraction-layer.md
> +This varies depending on the store, but the ratio is always the same. Data records are read many times more often than they are written. Therefore
```suggestion
This varies depending on the store, but the ratio is always the same. Data records are read way more often than they are written. Therefore
```

2021-05-11 11:44 UTC, PaddyS commented on concepts/framework/data-abstraction-layer.md
> +which pre-selects certain aggregations and writes them away optimized for the later reading process.
```suggestion
This is done in the DAL via the Entity Indexer pattern. As soon as a product record is written, the corresponding Product Indexer is triggered, which pre-selects
certain aggregations and writes them away optimized for the later reading process.
```

2021-05-12 11:25 UTC, PaddyS requested changes

2021-05-12 11:25 UTC, PaddyS commented on concepts/framework/http_cache.md
> +The cache invalidation of a storefront controller routes is controlled by the cache invalidation of the store API routes. For more information about Store API cache invalidation, you can refer to the
```suggestion
The cache invalidation of a storefront controller route is controlled by the cache invalidation of the store API routes. For more information about Store API cache invalidation, you can refer to the [Add Cache for Store Api Route Guide](../framework/store-api/add-caching-for-store-api-route.md).
```

2021-05-12 11:25 UTC, PaddyS commented on concepts/framework/http_cache.md
> +Therefore, for the invalidation of a controller route is controlled over the store api cache invalidation.
```suggestion
Therefore the invalidation of a controller route is controlled over the store api cache invalidation.
```

2021-05-12 11:25 UTC, PaddyS commented on guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md
> +In this guide you'll learn how to add a cache layer to your custom store API route. In this example, we will add a cache layer for the `ExampleRoute`, which created in the [Add store api route](./add
```suggestion
In this guide you'll learn how to add a cache layer to your custom store API route. In this example, we will add a cache layer for the `ExampleRoute`, which is created in the [Add store api route](./add-store-api-route.md) guide. For the cache invalidation we will write a invalidation subscriber.
```

2021-05-12 11:25 UTC, PaddyS commented on guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md
> +As you may already learned from the [Add store api route](./add-store-api-route.md) guide, we use abstract classes to make our routes more decoratable.
```suggestion
As you might have learned already from the [Add store api route](./add-store-api-route.md) guide, we use abstract classes to make our routes more decoratable.
```

2021-05-12 11:25 UTC, PaddyS commented on guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md
> +Cache invalidation is many times harder to implement than the actual caching. Finding the right balance between too much and too little invalidation is difficult.
```suggestion
Cache invalidation is much harder to implement than the actual caching. Finding the right balance between too much and too little invalidation is difficult.
```

2021-05-12 11:25 UTC, PaddyS commented on guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md
> +{% code title="<plugin root>/src/Core/Content/Example/SalesChannel/CachedExampleRoute.php" %}
Can you add the respective services.xml entry?
You can do so by using tabs:

```
{% tabs %}
{% tab title="CachedExampleRoute.php" %}
{% code title="<plugin root>/src/Core/Content/Example/SalesChannel/CachedExampleRoute.php" %}
// PHP Code here
{% endcode %}
{% endtab %}

{% tab title="services.xml" %}
{% code title="<plugin root>/src/Resources/config/services.xml" %}
// services.xml here
{% endcode %}
{% endtab %}
{% endtabs %}
```

For the services.xml, just the single entry will suffice:
```
<?xml version="1.0" ?>
<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="Swag\BasicExample\Core\Content\Example\SalesChannel\CachedExampleRoute">
            ...
        </service>
    </services>
</container>
```

2021-05-12 11:25 UTC, PaddyS commented on guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md
> +{% code title="<plugin root>/src/Core/Content/Example/SalesChannel/CacheInvalidationSubscriber.php" %}
Same here with the services.xml and the tabs

2021-05-17 07:10 UTC, elkmod commented on SUMMARY.md
> +        * [Add caching for store api route](guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md)
"Store API"

2021-05-17 07:10 UTC, elkmod commented on concepts/framework/data-abstraction-layer.md
> +This is reflected in Shopware as follows:
Extra empty line needed, otherwise Gitbook Markdown fails to show a new line.

2021-05-17 07:10 UTC, elkmod commented on concepts/framework/data-abstraction-layer.md
> +certain aggregations and writes them away optimized for the later reading process.
Why new line here?

2021-05-17 07:10 UTC, elkmod commented on guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md
> +In this guide you'll learn how to add a cache layer to your custom store API route. In this example, we will add a cache layer for the `ExampleRoute`, which created in the [Add store api route](./add
"Store API"

2021-05-17 13:37 UTC, merged