adds some more information and links, fixes "database" instead of "table"
shopware/docs pull request #318
Opened 2021-06-26 00:09 UTC by riconeitzel

2021-06-27 16:17 UTC, riconeitzel commented
I don't know, why the link tests failed … If I click the new link it works just fine. Anyone knows, what's wrong here?

2021-06-28 12:30 UTC, PaddyS requested changes

2021-06-28 12:30 UTC, PaddyS commented on guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md
> +* `propertyName`: The name of the property which should contain the associated entity of type `ExampleExtensionDefinition` in the `ProductDefinition`. Property names are usually camelCase (with first
```suggestion
* `propertyName`: The name of the property which should contain the associated entity of type `ExampleExtensionDefinition` in the `ProductDefinition`. Property names are usually camelCase, with the first character being lower cased.
```

2021-06-28 12:30 UTC, PaddyS commented on guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md
> +* `propertyName`: The name of the property which should contain the associated entity of type `ExampleExtensionDefinition` in the `ProductDefinition`. Property names are usually camelCase (with first
What do you think? :-)

2021-06-29 11:45 UTC, merged

2021-06-29 11:45 UTC, PaddyS commented
@riconeitzel Oof. Thanks once more! Really appreciate your work here. 🎉