NEXT-15802 - Build administration and storefront without database
shopware/docs pull request #342
Opened 2021-07-20 14:06 UTC by shyim

2021-07-21 12:33 UTC, PaddyS requested changes

2021-07-21 12:33 UTC, PaddyS commented on guides/hosting/installation-updates/deployments/databaseless.md
> + By default, without a database Shopware considers only the Administration to be built. To include the extensions without a database, you will need to use the `ComposerPluginLoader`. This determines
```suggestion
By default, without a database Shopware considers only the Administration to be built. To include the extensions without a database, you will need to use the `ComposerPluginLoader`. This determines the used plugins by looking up into the project installed dependencies. To get this working the plugin needs to be required in the system using `composer req [package/name]`.
```

2021-07-21 12:33 UTC, PaddyS commented on guides/hosting/installation-updates/deployments/databaseless.md
> + To use the `ComposerPluginLoader` you have to create a file like `bin/ci` and set up the CLI application with loader. There is an example:
```suggestion
 To use the `ComposerPluginLoader` you have to create a file like `bin/ci` and set up the CLI application with the loader. There is an example:
```

2021-07-21 12:33 UTC, PaddyS commented on guides/hosting/installation-updates/deployments/databaseless.md
> + # Compiling the Storefront without database
```suggestion
# Compiling the Storefront without database
```

2021-07-21 12:33 UTC, PaddyS commented on guides/hosting/installation-updates/deployments/databaseless.md
> + To compile the Storefront theme, we will need theme variables from the database. To allow compiling it without a database, it is possible to dump the variables to the private file system of Shopware
```suggestion
To compile the Storefront theme, we will need the theme variables from the database. To allow compiling it without a database, it is possible to dump the variables to the private file system of Shopware. This file system interacts with the local folder `files` by default, but to compile it, [it should be shared with a storage adapter like s3](../../infrastructure/filesystem.md). The configuration can be dumped using the command `bin/console theme:dump`, or it happens automatically when changing theme settings or assigning a new theme.
```

2021-07-21 12:33 UTC, PaddyS commented on guides/hosting/installation-updates/deployments/databaseless.md
> + By default, Shopware still tried to load configuration from database, in next step we will need to change the loader to `StaticFileConfigLoader`. To change that we will need to create a new file `co
```suggestion
By default, Shopware still tried to load configurations from the database, in the next step we will need to change the loader to `StaticFileConfigLoader`. To change that we will need to create a new file `config/packages/storefront.yaml` with the following content:
```

2021-07-21 12:33 UTC, PaddyS commented on guides/hosting/installation-updates/deployments/databaseless.md
> + This will force the theme compiler to use the static dumped file instead looking up in the database.
```suggestion
 This will force the theme compiler to use the static dumped file instead of looking into the database.
```

2021-07-22 07:31 UTC, PaddyS requested changes

2021-07-22 07:31 UTC, PaddyS commented on guides/hosting/installation-updates/deployments/databaseless.md
> +# Compiling the Storefront without database
```suggestion
## Compiling the Storefront without database
```

2021-07-23 06:13 UTC, elkmod commented on guides/hosting/installation-updates/deployments/databaseless.md
> + This guide requires Shopware 6.4.0 or higher.
Could you please mention the version requirement at the top of the article (right below the first heading) as described in this article: https://developer.shopware.com/docs/resources/guidelines/documentation/writing#maintaining-versions

2021-07-23 06:17 UTC, elkmod commented on guides/hosting/installation-updates/deployments/databaseless.md
> +It is common to prebuilt assets in professional deployments to deploy the finished assets to the production environment. This task is mostly done by an CI job which doesn't have access to the the pro
by "a" CI job [...].

2021-07-23 06:18 UTC, elkmod commented on guides/hosting/installation-updates/deployments/databaseless.md
> +By default, without a database Shopware considers only the Administration to be built. To include the extensions without a database, you will need to use the `ComposerPluginLoader`. This determines t
Maybe rephrase to:

By default, Shopware only builds the Administration without extensions if there is no database connection.

2021-08-03 09:33 UTC, elkmod approved these changes

2021-08-03 09:33 UTC, merged