Update add-data-translations.md
shopware/docs pull request #366
Opened 2021-08-06 14:42 UTC by do-car

I think it is worth mentioning how the main-entity definition class should be structured, in order to be able to get translated.

2021-08-09 11:55 UTC, PaddyS requested changes

2021-08-09 11:55 UTC, PaddyS commented on guides/plugins/plugins/framework/data-handling/add-data-translations.md
> +* a TranslationsAssociationField, with a reference to the ExampleTranslationDefinition
```suggestion
* a `TranslatedField` for the “name” field
* a `TranslationsAssociationField`, with a reference to the ExampleTranslationDefinition
```

2021-08-09 11:55 UTC, PaddyS commented on guides/plugins/plugins/framework/data-handling/add-data-translations.md
> +{% code title="/src/Core/Content/Example/ExampleDefinition.php" %}
```suggestion
{% code title="<plugin root>/src/Core/Content/Example/ExampleDefinition.php" %}
```

2021-08-09 11:55 UTC, PaddyS commented on guides/plugins/plugins/framework/data-handling/add-data-translations.md
> +    }
```suggestion
    [...]
```

2021-08-09 11:56 UTC, PaddyS commented
Whoa, thank you for your effort, @do-car! 🎉 
Just some minor changes that I'd like, besides that: Awesome!

2021-08-25 04:54 UTC, PaddyS commented
Hey @do-car,

just a friendly reminder. Would be awesome if you could apply the suggested changes! :-)

2021-08-30 08:25 UTC, do-car commented
> Hey @do-car,
> 
> just a friendly reminder. Would be awesome if you could apply the suggested changes! :-)
Hi @PaddyS, sorry for the wait :)

2021-08-31 07:27 UTC, PaddyS commented
Awesome, thank you @do-car! 🎉

2021-08-31 07:27 UTC, merged