Update customize-templates.md
shopware/docs pull request #373
Opened 2021-08-12 08:28 UTC by gregor-lohaus

If another developer wouldnt have given me the information that i had to assign the theme to the sales channel i would have been completely lost

2021-08-25 05:00 UTC, PaddyS requested changes
Hey @gregor-lohaus,

thank you very much for your pull request! 🎉 

However I am not too sure about the changes. Not having assigned a theme to a sales channel will result in **no template** at all being shown, regardless of this guide.

While I do understand the concern, it doesn't seem to fit to this guide, since it's a problem anyway and not really bound to this guide, you know?

Anyway, I suggested a minor change, would be great if you could apply those suggested changes first. :-)
I will then have a little chat with a colleague in order to figure out if this is the proper place for such an information text.

2021-08-30 09:22 UTC, gregor-lohaus commented
@PaddyS thanks for the review i updated the pull request with the requested changes

2021-09-02 09:21 UTC, PaddyS commented on guides/plugins/plugins/storefront/customize-templates.md
> +
```suggestion
```

2021-09-02 09:21 UTC, merged

2021-09-02 09:21 UTC, PaddyS commented
Thank you @gregor-lohaus 🎉