adding information about the need of associations
shopware/docs pull request #374
Opened 2021-08-17 08:50 UTC by wrongspot

I did this tutorial and after part 1 I expected the extension to load automatically by product enity load. 
In my opinion, there is no information that additional associations are needed.

2021-08-25 10:17 UTC, PaddyS requested changes
Hey @wrongspot,

thank you for your pull request!

Unfortunately, I don't really understand why it wouldn't work without your addition.
Your extension should load automatically when you're using the parameter mentioned [here](https://github.com/shopware/docs/pull/374/files#diff-a067680a577ef19b4820d4138937d15d2e62a4e08486b05a6c95775b0cb76922L115).

I've quickly tested it my example plugin that I had back then and it definitely works for me. But maybe I am just missing something here, so I'd love to hear back from you! 🙏

2021-08-25 12:31 UTC, wrongspot commented on guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md
> +Of course, registering your subscriber via services.xml
Hi @PaddyS

My expectation from the original tutorial is that I will create an EntityExtension according to the example, and that this extension will be available after loading the Entity. There is no indication that I also have to adjust the criteria object. Without "->addAssociation ('exampleExtension') exampleExtension is never loaded. In my example I register a subscriber to modify criteria object for that needs.

2021-09-01 20:22 UTC, wrongspot commented on guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md
> +Of course, registering your subscriber via services.xml
Hey @PaddyS, sorry for late response. You are absolutely right, of course. I totally overlooked the 'autoload' flag and it was false in my case. With that the PR is of course obsolete.

Best Regards

2021-09-02 09:22 UTC, PaddyS commented on guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md
> +Of course, registering your subscriber via services.xml
Thank you for your feedback, appreciate the effort though! 💙

2021-09-02 09:22 UTC, closed without merging