NEXT-13795 - Add Rate Limiter documentation
shopware/docs pull request #399
Opened 2021-09-20 12:36 UTC by Dominik28111

2021-09-20 12:40 UTC, shyim commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +First of all, we have to create a new rate limit in the `shopware.yaml` under `shopware.api.rate_limiter`.
for who is that guide?
Core or Plugin?

2021-09-20 12:43 UTC, Dominik28111 commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +First of all, we have to create a new rate limit in the `shopware.yaml` under `shopware.api.rate_limiter`.
Plugin

2021-09-20 18:21 UTC, JoshuaBehrens requested changes

2021-09-20 18:21 UTC, JoshuaBehrens commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +After we've injected the service into our API route, we cann call the limiter in our route method.
`we cann` -> `we can`

2021-09-20 18:21 UTC, JoshuaBehrens commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +- `key`: Key with which we want to limit the request e.g., the client IP.
Please speak that out loud quickly three times `with which we want` 😁 Maybe there is a better phrase for that

2021-09-22 10:28 UTC, JoshuaBehrens approved these changes
I like it. Especially the important addition regarding how to change with a plugin!

2021-09-22 10:28 UTC, JoshuaBehrens commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +head over to the [Symfony documentation](https://symfony.com/doc/current/service_container/compiler_passes.html).
Maybe promote https://tv.shopware.com/de/video/1140319/ ?

2021-09-24 07:24 UTC, shyim requested changes

2021-09-24 07:24 UTC, shyim commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +## Configuring rate limit
I would expect the default configuration documentation at https://developer.shopware.com/docs/guides/hosting/infrastructure

and not in an tutorial how to create an API route limiter

2021-09-24 07:24 UTC, shyim commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +`<platform root>/src/Core/Framework/Resources/config/packages/shopware.yaml` under `shopware.api.rate_limiter`.
Never touch core files

The users should create a `config/packages/shopware.yaml` with the override content

2021-09-24 07:24 UTC, shyim commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +        $this->rateLimiter->reset('example_route');
does the reset not need the key? like above at ensureAccepted

2021-10-01 08:26 UTC, PaddyS requested changes

2021-10-01 08:26 UTC, PaddyS commented on guides/hosting/infrastructure/rate-limiter.md
> +The `time_backoff` policy is build by Shopware itself. It enables you to throttle the request in multiple steps with different waiting times.
```suggestion
The `time_backoff` policy is built by Shopware itself. It enables you to throttle the request in multiple steps with different waiting times.
```

2021-10-01 08:26 UTC, PaddyS commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +First of all, we have to create a new configuration file for our rate limit. In this example we named it `rate_limiter.yaml` located in `<plugin root>/src/Ressources/config/`.
```suggestion
First of all, we have to create a new configuration file for our rate limit. In this example we named it `rate_limiter.yaml` located in `<plugin root>/src/Resources/config/`.
```

2021-10-01 08:26 UTC, PaddyS commented on guides/plugins/plugins/framework/rate-limiter/add-rate-limiter-to-api-route.md
> +with a higher priority, otherwise it will be built to late.
```suggestion
with a higher priority, otherwise it will be built too late.
```

2021-10-05 11:41 UTC, elkmod approved these changes

2021-10-05 11:45 UTC, merged