Update message-queue.md
shopware/docs pull request #401
Opened 2021-09-21 19:52 UTC by tinect

I had a discussion with certified hoster... I reported I'd like to have something like system or supervisor for running messenger:consume. We are updating our products multiple time a time. While having f.e. products with many variants, the related messenges can exceed the time-limit. So, we had >80 CRONJOBS running, while just set three ;-) - not to tell they were blocking each other and consuming the complete capacity of the server.
The hoster could not find any related information **at** shopware why not to use cronjobs.

2021-09-24 07:19 UTC, shyim requested changes

2021-09-24 07:19 UTC, shyim commented on guides/hosting/infrastructure/message-queue.md
> +It's recommended to run one or more `messenger:consume`-workers. To automatically start the processes again after they stopped because of exceeding the given limits you can use a process control syst
isn't upstart dead?

We should recommend systemd as default

2021-09-24 07:19 UTC, shyim commented on guides/hosting/infrastructure/message-queue.md
> +Find here the docs of symfony: https://symfony.com/doc/current/messenger.html#deploying-to-production
```suggestion
Find here the docs of Symfony: https://symfony.com/doc/current/messenger.html#deploying-to-production  
```

2021-09-27 16:40 UTC, shyim approved these changes

2021-09-29 08:28 UTC, PaddyS commented
Love it! Thank you @tinect 🎉

2021-09-29 08:28 UTC, merged