DX-60 - Add a custome flow builder action guide
shopware/docs pull request #435
Opened 2021-11-24 07:24 UTC by nguyenquangtin

2021-11-24 15:50 UTC, elkmod requested changes

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +You also should be familiar with [Add customer event](../event/add-custom-event.md) to know how to create an event.
Typo: "Add custom event"

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +
Should we also link to the (to be written) flow builder concept, so people understand how it works in general?

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +You can refer to the [Overview Events and Actions](https://shopware.atlassian.net/wiki/spaces/~m.friedmann/pages/18987974805/Flow+Builder+-+Overview+Events+and+Actions) to read triggers and actions d
This is an internal link and is not gonna work for documentation readers.

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +
What are those interfaces/classes used for? Maybe add a little description for that.

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +In this example, we will name it `ExampleEvent` to some actions related to customer when dispatching this event. It will be placed in the directory `<plugin root>/src/Core/Checkout/Customer/Event`. O
The first sentence doesn't sound right.

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +In this example, we will name it `ExampleEvent` to some actions related to customer when dispatching this event. It will be placed in the directory `<plugin root>/src/Core/Checkout/Customer/Event`. O
Typo: "Has to implement"

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +Please note that you subscriber you has high priority to make sure your event is added before any subscriber`BusinessEventCollectorEvent` to prevent missing aware or action. I set 1000 for `onAddExam
There's one `you` too much in this sentence and a space ` ` missing before `BusinessEventCollectorEvent`.

> I set priority to 1000 for the `onAddExampleEvent` action:

2021-11-24 15:50 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +Well done, you are successfully created your own flow trigger.
"you have successfully"

2021-11-29 08:20 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +## Existing triggers and actions
This list is great, however it is better placed within a dedicated page in the "References" section of our documentation. 

E.g. Resources > References > Core References > Flow Reference

![image](https://user-images.githubusercontent.com/7780750/143831963-f2be3cff-b3ee-4053-ba91-f3ccda1ada15.png)

2021-11-29 08:21 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +| contact_form.send<                                     | Triggers when a contact form is send                                                              | Send mail
Small typo in `contact_form.send*<*`

2021-11-29 08:22 UTC, elkmod requested changes
Just small adapations + extracting the whole event reference to a separate "Reference" page located under Resources > References > Core Reference > Flow Reference.

2021-12-02 03:56 UTC, nguyenquangtin commented
@Christian-Rades 
I have updated the SUMMARY.md. Please help me review it.

2021-12-02 08:51 UTC, Christian-Rades commented
Looks good :+1:

2021-12-03 09:01 UTC, elkmod commented on guides/plugins/plugins/framework/flow/README.md
> +# Message Queue
This is incorrect :) Just use `# Flow` instead, please.

2021-12-03 09:06 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +<div data-gb-custom-block data-tag="hint" data-style='info'>
This is not going to display properly. Please use gitbook syntax and add the hint at the beginning of the article.

For reference:
 * https://gitbook.gitbook.io/git-sync/hints
 * https://github.com/GitbookIO/git-sync-normalization/blob/master/hints.md

The correct markup for displaying hints is this:

{% hint style="info" %}
This functionality is available starting with Shopware 6.4.3.0.
{% endhint %}

2021-12-03 10:18 UTC, elkmod approved these changes

2021-12-03 10:22 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +## Add custom action in Administrator
Typo: "Administration"

2021-12-03 10:29 UTC, elkmod requested changes

2021-12-03 10:29 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +### Define action scope
Whitespace before heading

2021-12-03 10:29 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-trigger.md
> +You can refer to the table below to read [all existing triggers and actions](../../../../../resources/core-reference/flow-reference.md) in detail.
There is no table below, since it was moved, so maybe adapt that phrase :)

2021-12-03 10:29 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +![Flow Builder demo](../../../.gitbook/assets/flow-builder-demo.gif)
The relative links are not correct I think - could you please double check these?

```
guides/plugins/plugins/framework/flow/add-flow-builder-action.md
../framework
../plugins

=> 
/guides/plugins/.gitbook/assets/...      
```

2021-12-03 15:11 UTC, nguyenquangtin commented
@elkmod 
Thanks for your help Dominic. I've resolved those minor issues and update the block codes. Please help me to check it again when you have time. Have a nice weekend.

2021-12-06 08:05 UTC, elkmod approved these changes

2021-12-06 09:12 UTC, nguyenquangtin commented
@elkmod  Please let me know if you need further support.

2021-12-06 09:30 UTC, merged