NEXT-17832 - document theme inheritance
shopware/docs pull request #445
Opened 2021-12-02 14:07 UTC by ssltg

Updated theme config documentation for the new key 'configInheritance'

2021-12-02 15:39 UTC, tobiasberge commented on guides/plugins/themes/theme-configuration.md
> +different saleschannels with specific changes only needed for a single saleschannel.
```suggestion
different sales channels with specific changes only needed for a single sales channel.  
```

2021-12-02 15:42 UTC, tobiasberge commented on guides/plugins/themes/theme-configuration.md
> +for a more detailed example.
Maybe something additional like... ?

All configuration fields and their values from the mentioned themes in `configInheritance ` are available inside the current theme, unless they are explicitly overwritten. This way custom themes can be extended without copying their configuration inside the `theme.json`.

2021-12-02 15:43 UTC, tobiasberge commented on guides/plugins/themes/theme-configuration.md
> +special saleschannel or for a special time. See [Theme inheritance](../plugins/themes/add-theme-inheritance.md)
```suggestion
special sales channel or for a special time. See [Theme inheritance](../plugins/themes/add-theme-inheritance.md) 
```
Once again, not sure.

2021-12-02 15:45 UTC, tobiasberge commented on guides/plugins/themes/theme-inheritance-configuration.md
> +your icons. But on a special week in the year you have additional requirements for a special design, like a discount
Maybe we should not mention icons here because right now icons cannot really be handled via theme.json. Maybe "and you configuration fields"

2021-12-03 08:36 UTC, ssltg commented on guides/plugins/themes/add-theme-inheritance.md
> +The `asset` section. If you want to use assets from the `@SwagBasicExampleTheme` you have add it to the list here as
changed it

2021-12-03 08:40 UTC, ssltg commented on guides/plugins/themes/add-theme-inheritance.md
> +Finally, the `configInheritance` section will use the field configuration from the given themes and defines the last
Yeah, I changed it. The parentTheme will be the last Theme that is NOT the current theme

2021-12-13 10:48 UTC, tobiasberge approved these changes

2021-12-14 15:06 UTC, elkmod commented
Please remove all the line breaks within paragraphs. Probably, that's a setting in your editor.

2021-12-14 15:19 UTC, ssltg commented
> Please remove all the line breaks within paragraphs. Probably, that's a setting in your editor.

@elkmod I removed the line breaks.

2021-12-14 15:32 UTC, elkmod requested changes

2021-12-15 09:56 UTC, ssltg commented on guides/plugins/themes/theme-inheritance-configuration.md
> +Imagine you have a theme which is applying your corporate design to the storefront. With your colors, your logo and
Both is correct but I will change it.

2021-12-17 08:10 UTC, tobiasberge approved these changes

2021-12-30 11:38 UTC, elkmod approved these changes

2021-12-30 11:40 UTC, elkmod commented on guides/plugins/themes/theme-configuration.md
> +
Since this is a new "feature", could you please add a hint at this place?

2021-12-30 11:40 UTC, elkmod commented on guides/plugins/themes/theme-inheritance-configuration.md
> +
Please also add the version hint here.

2022-01-03 08:54 UTC, merged