Added required info about cart processors to add-cart-items.md
shopware/docs pull request #450
Opened 2021-12-07 22:33 UTC by wirduzen-felix

**Attention:** these changes are referencing add-cart-processor-collector.md which doesn't seem to be published, yet.

add-cart-items.md was missing information about cart processors. These are required for the line items to be persisted into the database and for them to be dispatched to the storefront. Furthermore this pull request replaces the "hardcoded" line item type with a constant.

2021-12-08 12:11 UTC, elkmod requested changes

2021-12-08 12:11 UTC, elkmod commented on guides/plugins/plugins/checkout/cart/add-cart-items.md
> +{% endcode %}
Could you add a whitespace before and after the codeblocks, please? :)

2021-12-08 12:11 UTC, elkmod commented on guides/plugins/plugins/checkout/cart/add-cart-items.md
> +Now register this processor in your `services.xml` like this:
Same here.

2021-12-08 12:18 UTC, elkmod commented on guides/plugins/plugins/checkout/cart/add-cart-items.md
> +Of course you can use processors to do much more than this. Have a look at [adding cart processors and collectors](./add-cart-processor-collecor.md).
The link contains a typo "collecor"

2021-12-08 12:20 UTC, elkmod commented
Hi @wirduzen-felix - thank you for your contribution! I created a new PR #451 to add that guide to the navigation, however, I want to check with the team first - maybe there's a reason it was not published yet. Once we figured that out, we can merge your PR :)

2021-12-08 12:25 UTC, wirduzen-felix commented
@elkmod Thank you very much :). I added the whitespaces and fixed the typo.

2021-12-14 14:46 UTC, elkmod commented
Awesome - thanks for your help - PR is merged!

2021-12-14 14:46 UTC, merged