NEXT-19965 - add custom endpoint script docs
shopware/docs pull request #497
Opened 2022-02-22 09:58 UTC by keulinho

Add docs for new 6.4.9.0 app script features: Custom endpoints & lifecycle scripts

2022-02-22 10:47 UTC, JoshuaBehrens commented
This is what the new apps are capable of? IN SANE!

2022-02-22 11:03 UTC, shyim requested changes

2022-02-22 13:42 UTC, keulinho commented
@JoshuaBehrens yes indeed! Already landed in trunk

2022-02-22 17:20 UTC, JoshuaBehrens commented
:scd_hyped:

2022-02-23 11:26 UTC, shyim approved these changes

2022-03-11 08:47 UTC, Christian-Rades approved these changes

2022-03-11 08:53 UTC, merged