NEXT-16225 - Added custom entities documentation
shopware/docs pull request #501
Opened 2022-03-02 10:06 UTC by OliverSkroblin

2022-03-02 10:28 UTC, keulinho commented on guides/plugins/apps/custom-data/custom-entities.md
> +You can add custom entities to Shopware and thus extend the functionality of your shop.
can you add a little bit more explanatory text on where to use the feature?

E.g. if you want to store custom complex data in the shopware DB you can use custom entities to do so...

2022-03-04 07:54 UTC, keulinho commented on guides/plugins/apps/custom-data/custom-entities.md
> +```markup
```suggestion
```xml
```
code higlighting will be better

2022-03-19 19:17 UTC, JoshuaBehrens requested changes

2022-03-19 19:17 UTC, JoshuaBehrens commented on guides/plugins/apps/custom-data/custom-entities.md
> +## Functionality
New lines after headlines is nice

2022-03-24 08:38 UTC, OliverSkroblin commented on guides/plugins/apps/custom-data/custom-entities.md
> +## Permissions
```suggestion
## Permissions

```

2022-03-24 08:38 UTC, OliverSkroblin commented on guides/plugins/apps/custom-data/custom-entities.md
> +## Functionality
```suggestion
## Functionality

```

2022-03-25 10:21 UTC, elkmod approved these changes

2022-03-25 11:06 UTC, JoshuaBehrens commented
Maybe I missed it, but I am missing a hint. I see references from the blog the product. Are they added automatically from product to blog as extension as well? This way you can also query this relation via API. If this already happens it would be cool if it is mentioned.

2022-05-04 08:30 UTC, elkmod approved these changes

2022-05-04 08:30 UTC, merged