NEXT-20949 - Metrics in Shopware
shopware/docs pull request #543
Opened 2022-04-12 12:02 UTC by fschmtt

2022-04-13 12:27 UTC, SebastianFranze requested changes

2022-04-13 14:35 UTC, fschmtt commented on guides/plugins/plugins/framework/metrics/README.md
> +        $theme = $this->themeRepository->search($criteria, $context)->first();
Switched to plain SQL.

2022-04-13 14:59 UTC, fschmtt commented on guides/plugins/plugins/framework/metrics/README.md
> +| `$metadata` | `::withMetadata()` | The metadata are additional information that usually are the same for all metrics.                 |
i also like it better to have those both "collections" separated from each other, so the clients can easily distinguish between them. and they can ultimately decide how to handle them - there might be clients that simply merge both, others might want to transform the metatag's keys and prefix them or sth.

there's quite a variety of possible clients/backends that i would like to give implementations the possibility to handle those data differently.

from a technical point of view, yes, both seem to be the same, but as metrics are more likely to be "business" metrics, we should also keep this in mind, when designing the interfaces IMO.

2022-04-20 08:41 UTC, xPand4B requested changes

2022-04-20 08:41 UTC, xPand4B commented on guides/plugins/plugins/framework/metrics/README.md
> +For more resource intensive metrics it's better to use a collector, that is run once a day by scheduled task.
```suggestion
For more resource intensive metrics it's better to use a collector, that will run once a day by scheduled task.
```

2022-04-20 08:41 UTC, xPand4B commented on guides/plugins/plugins/framework/metrics/README.md
> +| `$value`    | `::withValue()`    | The value of the metric must be one of <code>bool                                                  |int|float|string</code> and mainly depends on the metric's typ
This one has 4 columns in a 3 column table 🤔

2022-04-20 08:41 UTC, xPand4B commented on guides/plugins/plugins/framework/metrics/README.md
> +To provide additional custom metadata, see the corresponding section later in this article.
Maybe add a link to the part mentioned?

2022-04-20 08:41 UTC, xPand4B commented on guides/plugins/plugins/framework/metrics/README.md
> +        CustomerRegisterEvent::class;
I think the `return` statement is missing

```suggestion
        return CustomerRegisterEvent::class;
```

2023-01-12 06:50 UTC, sushmangupta commented
Followup- the feature is yet to be implemented.

2023-07-10 14:02 UTC, closed without merging