B2B-871 - B2B-Suite administration docs
shopware/docs pull request #554
Opened 2022-04-20 10:11 UTC by dfrancos-hub

2022-04-26 09:33 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/acl-routing.md
> +<a href="{url action=assign}" class="{b2b_acl controller=b2broleaddress action=assign}">
This is no twig, but smarty code. Please update these examples

2022-04-26 09:36 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +`AjaxPanel` is a jQuery based extension to the Shopware Frontend Framework. It mimics `iFrame` behaviour by integrating content from different controller actions through ajax into a single view and i
"jQuery based" is not up to date. You could replace this with "... is a mini-framework based on storefront plugins."

2022-04-26 09:36 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +    data-url="{url controller="b2bcontact" action="grid"}"
Replace smarty-Code with Twig-Code.

2022-04-26 09:38 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +After `$(document).ready()` is triggered it will trigger a XHR GET-Request and replace it's inner html with the responses content. Now all clicks on links and form submits inside the container will b
We are not using jQuery anymore, but the idea is still correct. You could just replace this with "After the document is ready, the ajax panel will trigger ...."

2022-04-26 09:38 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +<p class="ajax-panel-link" data-href="{url controller="b2bcontact" action="grid"}">Click</p>
Replace smarty-Code with Twig-Code.

2022-04-26 09:39 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +    data-url="{url controller="b2bcontact" action="grid"}"
Replace smarty-Code with Twig-Code.

2022-04-26 09:39 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +    data-plugins="b2bAjaxPanelFormDisable"
We are not using the b2b-Prefix anymore. This would be "ajaxPanelFormDisable" instead.

2022-04-26 09:39 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +    data-url="{url controller="b2bcontact" action="grid"}"
Replace smarty-Code with Twig-Code.

2022-04-26 09:40 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +    data-plugins="b2bAjaxPanelFormDisable"
We are not using the b2b-Prefix anymore. This would be "ajaxPanelFormDisable" instead.

2022-04-26 09:40 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +<div class="b2b--ajax-panel" data-url="{url controller="b2bcontact" action="grid"}" data-id="grid">
Replace smarty-Code with Twig-Code.

2022-04-26 09:40 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +<div class="b2b--ajax-panel" data-url="{url controller="b2bcontact" action="edit"}" data-ajax-panel-trigger-reload="grid">
Replace smarty-Code with Twig-Code.

2022-04-26 09:40 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
> +This `TreeSelect` plugin allows to display a tree view with enabled drag and drop. In the view the `div` element needs the class `is--b2b-tree-select-container` and the data attribute `data-move-url=
Replace smarty-Code with Twig-Code.

2022-04-26 09:42 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/product-search.md
> +Our product search is a small jQuery Plugin which allows you to create input fields with autocompletion for products. A small example is shown below. The plugin deactivates the default autocompletion
"Storefront Plugin" instead of "jQuery Plugin"

2022-05-04 08:21 UTC, bschulzebaek requested changes
Last requested changes by me, looks fine overall. But please also wait for @MartinKrzykawski feedback, due to the high amount of backend information

2022-05-04 08:21 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/modal-component.md
> +```
Missing language "Twig", this breaks the output.

2022-05-04 08:21 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/modal-component.md
> +```
Missing language "Twig", this breaks the output.

2022-05-04 08:21 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/modal-component.md
> +```
Missing language "Twig", this breaks the output.

2022-05-04 08:21 UTC, bschulzebaek commented on products/editions/enterprise-edition/b2b-suite/guides/storefront/modal-component.md
> +```
Missing language "Twig", this breaks the output.

2022-05-09 13:42 UTC, MartinKrzykawski approved these changes

2022-05-10 14:42 UTC, bschulzebaek approved these changes

2022-05-12 06:44 UTC, merged