RouteScope is gone :-)
shopware/docs pull request #635
Opened 2022-07-12 14:24 UTC by tinect

fix: remove superfluous uses of RouteScope, update
fix: remove wrong annotation of multiple @Route

Basically come into it because this coming from docs is really invalid:
```
* @Route(defaults={"_routeScope"={"storefront"}})
* @Route("/example", name="frontend.example.example", methods={"GET"})
```

2022-07-12 14:38 UTC, Dominik28111 requested changes

2022-07-12 14:40 UTC, Dominik28111 approved these changes

2022-07-12 21:44 UTC, shyim commented
You need to describe both ways until next major. As the new way does not work in the entire 6.4 line

2022-07-13 04:58 UTC, tinect commented
Hey @shyim 
Why haa it been changed in docs by shopwsre when both parts have to be described?

This PR just removes useless and wrong content.

So it's your turn to readd the old content, too, isn't it? :-)

2022-07-13 06:25 UTC, shyim commented
I would rather describe how it works in the deprecated way, instead replacing it with an all new solution which was implemented in a minor version. The docs versioning works in major version, so the written doc has to work in all 6.4.x versions.

Maybe just let the old stuff there and a hint that the route scope has been moved in newer versions

2022-07-13 06:55 UTC, tinect commented
Hey @shyim 
I've not removed relevant content. I just removed wrong content introduced by https://github.com/shopware/docs/pull/574

Should shopware just revert it and add new content? xD

2022-07-13 11:42 UTC, Christian-Rades commented on guides/plugins/plugins/storefront/add-custom-controller.md
@shyim I think guides should represent current best practices. That's why think a simple hint about the old way of defining a route scope is enough.
```suggestion

{% hint style="info" %}
Prior to Shopware 6.4.11.0 the `_routeScope` was configured by a dedicated annotation: `@RouteScope`. This way of defining the route scope is deprecated for the 6.5 major version.
{% endhint %}

```

2022-07-13 11:42 UTC, Christian-Rades commented on guides/plugins/plugins/storefront/add-custom-controller.md
```suggestion

{% hint style="info" %}
Prior to Shopware 6.4.11.0 the `_routeScope` was configured by a dedicated annotation: `@RouteScope`. This way of defining the route-scope is deprecated for the 6.5 major version.
{% endhint %}

```

2022-07-15 17:38 UTC, Christian-Rades approved these changes

2022-07-15 17:39 UTC, merged