adding information about the configuration object
shopware/docs pull request #678
Opened 2022-09-09 20:00 UTC by NinjaArmy

The CMS-Guide is not complete. The configuration object has two more options:
- removable
- hidden

I think this options should be mentioned in the docs as well.

2022-09-12 20:31 UTC, JoshuaBehrens commented
👍 it is used by app vendors already. It is basically public API

2022-09-14 07:08 UTC, sushmangupta requested changes

2022-09-14 07:08 UTC, sushmangupta commented on guides/plugins/plugins/content/cms/add-cms-element.md
> +| removable (optional| Removes the replace element icon. |
Please add the closing bracket and spacing where necessary.

2022-09-21 07:14 UTC, sushmangupta approved these changes
Thank you for making the changes @NinjaArmy . :)

2022-09-21 07:15 UTC, merged