Add a guide for creating own twig functions with new example
shopware/docs pull request #710
Opened 2022-10-09 13:19 UTC by Tschucki

Referring to [PR 462](https://github.com/shopware/docs/pull/462)

I added a new example with md5.

2023-02-05 11:45 UTC, Tschucki commented
Bump.

2023-07-20 13:16 UTC, ssltg approved these changes
Thanks for your contribution and patience (sometimes things get lost in the daily business, sorry for that).

2023-07-20 13:19 UTC, ssltg commented
@Tschucki Maybe you have to push again to rerun the checks.

2023-07-24 07:23 UTC, tobiasberge approved these changes

2023-08-03 15:12 UTC, sushmangupta requested changes

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +In order to create your own Twig Function for your plugin, you first need a plugin as base. Therefore, you can refer to the [Plugin Base Guide](../plugin-base-guide.md).
```suggestion
In order to create your own twig function for your plugin, you first need a plugin as base. Therefore, you can refer to the [Plugin Base Guide](../plugin-base-guide.md).
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +# Add custom Twig Functions
```suggestion
# Add Custom Twig Functions
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +## Creating Twig Function
```suggestion
## Creating twig function
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +In the following sections we will create and expand all necessary files for the Twig function to work. These are actually exactly 2 files. First the PHP file with the Twig Functions itself and the se
```suggestion
In the following sections, we will create and expand all necessary files for the twig function to work. There are two such files:
* PHP file with the twig functions itself and
* Services.xml
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +### Creating the Twig Function
```suggestion
### Creating the twig function
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +Let's have a look at the created file.
```suggestion
For clarity, create a folder named `Twig` within the `src` folder. Then create a new php file with desired file name within the `Twig` folder. Refer to the below example :
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +What is still missing is the registration of the service in the DI container.
```suggestion
Of course, you can do everything in the `createMd5Hash` function that PHP can do, but the service.xml handles registration of the service in the DI container.
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +After all that is done, you can access this Twig function within your plugin.
```suggestion
Once done, you can access this `TwigFunction` within your plugin.
```

2023-08-03 15:12 UTC, sushmangupta commented on guides/plugins/plugins/storefront/add-custom-twig-function.md
> +### Use the Twig function in your template
```suggestion
### Use twig function in template
```

2023-08-03 15:25 UTC, sushmangupta commented
@Tschucki , apologies for the delayed response. 
I have added a few suggestions. Can you please take a look at it possibly?

2023-08-09 15:33 UTC, sushmangupta approved these changes

2023-08-09 15:34 UTC, sushmangupta commented
Sorry for the delayed response and thanks for contributing @Tschucki :)

2023-08-09 15:34 UTC, merged