NTR - fixed codestyle of example and typos
shopware/docs pull request #714
Opened 2022-10-10 20:29 UTC by AegeliusFuneris

2022-10-10 20:31 UTC, marcelbrode approved these changes

2022-10-12 07:21 UTC, Christian-Rades requested changes

2022-10-12 07:21 UTC, Christian-Rades commented on guides/plugins/plugins/content/cms/add-cms-element-via-admin-sdk.md
> +```twig
Please wrap your code in a `{% raw %}` statement
```suggestion
{% raw %}
```twig
```

2022-10-12 07:21 UTC, Christian-Rades commented on guides/plugins/plugins/content/cms/add-cms-element-via-admin-sdk.md
>  ```
Add a `{% endraw %}` statement here.

2022-10-13 06:42 UTC, marcelbrode approved these changes

2022-10-13 07:54 UTC, Christian-Rades approved these changes

2022-10-13 07:54 UTC, merged

2022-10-13 07:55 UTC, Christian-Rades commented
Thank you for your contribution 🎉