NEXT-22868 - Modal in actions should be optional
shopware/docs pull request #716
Opened 2022-10-11 13:54 UTC by thuanlv287

2022-10-11 14:43 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +Images, your action is already in the action list after <strong>Step 1.</strong>
Could we have a link to step 1 here? `[#step-1-link](first step)`.

2022-10-11 14:46 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +After you click on the action, the new sequence will automatically add to the action list like this:
```suggestion
Now, after you click on the action, the new sequence will automatically be added to the action list like this:
```

2022-10-11 15:08 UTC, sushmangupta requested changes

2022-10-11 15:08 UTC, sushmangupta commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
>  Now you can view the whole demo for this custom Flow builder trigger and action as below.
```suggestion
You can view the whole demo for this custom Flow Builder trigger and action below:
```

2022-10-11 15:30 UTC, sushmangupta approved these changes

2022-10-12 07:12 UTC, elkmod commented on guides/plugins/plugins/framework/flow/add-flow-builder-action.md
> +Imagine, your action is already in the action list after [the first step](https://developer.shopware.com/docs/guides/plugins/plugins/framework/flow/add-flow-builder-action#step-1-show-action-label-in
Please use a relative link here.

2022-10-17 07:58 UTC, elkmod approved these changes

2022-10-17 07:58 UTC, merged