commercial/custom-pricing - Fix link to plugin install guide, adjust guide for DELETE
shopware/docs pull request #781
Opened 2022-11-24 12:45 UTC by swsrmes

2022-11-24 13:46 UTC, MarcelSchmaeing approved these changes
looks good to me

2022-11-30 07:08 UTC, leichteckig approved these changes

2022-11-30 07:59 UTC, sushmangupta commented on guides/plugins/plugins/api/Customer-specific-pricing.md
> +For the `delete` action, the workflow is that the operation accepts 3 different arrays of ids: `customerIds`, `productIds` or `customerGroupIds`. Here you can specify any combination of these id arra
```suggestion
For the `delete` action, the workflow operation accepts 3 different array of ids: `customerIds`, `productIds` or `customerGroupIds`. Here, you can specify any combination of these id arrays, with an exception that the API route must have at least one UUID supplied in one of the id arrays (`customerIds`, `productIds` or `customerGroupIds`)
```

2022-11-30 12:53 UTC, elkmod requested changes

2022-12-02 10:22 UTC, elkmod commented on SUMMARY.md
> +    * [Custom Pricing](guides/plugins/plugins/api/Customer-specific-pricing.md)
```suggestion
    * [Custom Pricing](guides/plugins/plugins/api/customer-specific-pricing.md)
```

2022-12-02 12:02 UTC, sushmangupta approved these changes

2022-12-13 12:42 UTC, elkmod approved these changes

2022-12-13 12:43 UTC, merged