Add devenv
shopware/docs pull request #807
Opened 2023-01-04 08:26 UTC by shyim

2023-01-04 10:24 UTC, fschmtt commented
Open tasks:
- [ ] PhpStorm setup: path to PHP and other binaries
- [ ] PhpStorm setup: connect to DB using DB Tool Window (alternative to using adminer)
- [ ] `env.` file: use `127.0.0.1` instead of `localhost` in `DATABASE_URL`
- [ ] Add section "Known issues": Large repo causes slow shell (https://github.com/cachix/devenv/issues/257)
- [ ] Guide on `devenv gc`

2023-01-04 10:27 UTC, fschmtt commented on SUMMARY.md
> +  * [Devenv](guides/installation/devenv.md)
The devenv guide should also be included on the overview page

2023-01-05 08:00 UTC, Christian-Rades approved these changes

2023-01-05 12:48 UTC, sushmangupta requested changes

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +To be able to use unfree software, you have to allow that:
```suggestion
By default, `shopware/platform` uses unfree software like Blackfire. To be able to use unfree software, you have to *allow* it:
```

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +If you are already using Symfony Flex, you can require a Composer package to get a basic devenv configuration:
```suggestion
If you are already using Symfony Flex, you require a composer package to get a basic devenv configuration:
```

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +{% endhint %}
```suggestion
{% hint style="warning" %}
Make sure that the ports for the services are not already in use, or else the command will fail.
{% endhint %}
```

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +Still inside the project directory, run the following command to initialize Shopware:
```suggestion
Inside the project directory, run the following command to initialize Shopware:
```

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +If you wish to seamlessly switch between multiple development environments which use devenv we recommend to install [direnv](https://direnv.net/).
```suggestion
If you wish to switch between multiple development environments which use devenv seamlessly, we recommend installing [direnv](https://direnv.net/).
```

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +Here's an overview of services Shopware provides by default and how you can access them:
```suggestion
Here is an overview of services Shopware provides by default and how you can access them:
```

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +To customize the predefined services to match your needs, e.g. changing the virtual host, database name or environment variables, you can create `devenv.local.nix` to override the service definitions
```suggestion
To customize the predefined services to match your needs, e.g., changing the virtual host, database name, or environment variables, you can create `devenv.local.nix` to override the service definitions.
```

2023-01-05 12:48 UTC, sushmangupta commented on guides/installation/devenv.md
> +Be aware that you cannot connect using the `localhost` socket, you must use `127.0.0.1` instead.
```suggestion
Be aware that you cannot connect using the `localhost` socket. Instead, you must use `127.0.0.1`.
```

2023-01-05 12:57 UTC, Christian-Rades approved these changes

2023-01-05 13:07 UTC, Christian-Rades approved these changes

2023-01-05 14:40 UTC, merged