Fix typos, rephrase words and improve readability
shopware/docs pull request #813
Opened 2023-01-06 21:27 UTC by fschmtt

2023-01-06 21:32 UTC, shyim approved these changes

2023-01-09 07:20 UTC, fschmtt commented on guides/installation/flex.md
> +This creates a new project in the `<project-name>` directory. The `dev-flex` version constraint installs the latest version of Shopware. The constraint `dev-flex` will be removed when the template is
```suggestion
This creates a new project in the `<project-name>` directory. The `dev-flex` version constraint installs the latest version of Shopware. The constraint `dev-flex` will be removed once the template is generally available.
```

2023-01-09 14:12 UTC, sushmangupta requested changes
@fschmtt,
"composer" is always written in small case throughout the dev doc, unlike in this article. Do you agree with this?
Else, we'll need to talk about it.

2023-01-09 14:12 UTC, sushmangupta commented on guides/installation/flex.md
> +The template contains all Shopware bundles like `shopware/administration`, `shopware/storefront` and `shopware/elasticsearch`. If you don't need any of them, you can uninstall it with:
```suggestion
The template contains all Shopware bundles like `shopware/administration`, `shopware/storefront` and `shopware/elasticsearch`. If you don't need any, then you can uninstall them with:
```

2023-01-09 16:30 UTC, fschmtt commented
> @fschmtt, "composer" is always written in small case throughout the dev doc, unlike in this article. Do you agree with this? Else, we'll need to talk about it.

"Composer", is, like Symfony, Shopware etc., a "brand" name and should thus be written capitalized in regular text passages IMO.

I think we didn't really pay attention to this (not only for Composer but other "brand" names, too) so far, but IMO we should.

WDYT @sushmangupta?

2023-01-09 16:59 UTC, sushmangupta approved these changes

2023-01-09 17:02 UTC, sushmangupta commented
@fschmtt, Yes I totally agree with you. I will make this correction overall. 
Let me know if you observe any other brand names that need a correction in our dev docs.

2023-01-11 06:49 UTC, merged