NEXT-24709 - Add payment and shipping method route hooks
shopware/docs pull request #825
Opened 2023-01-20 11:50 UTC by mstegmeyer

2023-01-20 11:56 UTC, raknison approved these changes

2023-01-20 12:14 UTC, lernhart approved these changes

2023-01-25 09:44 UTC, sushmangupta requested changes
Updated hyperlinks to point to a specific topic.

2023-01-25 09:44 UTC, sushmangupta commented on resources/references/app-reference/script-reference/script-hooks-reference.md
> +| **Available Services** | [repository](./data-loading-script-services-reference.md#RepositoryFacade)<br>[config](./miscellaneous-script-services-reference.md#SystemConfigFacade)<br>[store](./data-lo
```suggestion
| **Available Services** | [repository](./data-loading-script-services-reference.md#RepositoryFacade)<br>[config](./miscellaneous-script-services-reference.md#servicesconfig-shopwarecoresystemsystemconfigfacadesystemconfigfacade-systemconfigfacade)<br>[store](./data-loading-script-services-reference.md#servicesstore-shopwarecoreframeworkdataabstractionlayerfacadesaleschannelrepositoryfacade-saleschannelrepositoryfacade)<br> |
```

2023-01-25 09:44 UTC, sushmangupta commented on resources/references/app-reference/script-reference/script-hooks-reference.md
> +| **Available Services** | [repository](./data-loading-script-services-reference.md#RepositoryFacade)<br>[config](./miscellaneous-script-services-reference.md#SystemConfigFacade)<br>[store](./data-lo
```suggestion
| **Available Services** | [repository](./data-loading-script-services-reference.md#RepositoryFacade)<br>[config](./miscellaneous-script-services-reference.md#servicesconfig-shopwarecoresystemsystemconfigfacadesystemconfigfacade-systemconfigfacade)<br>[store](./data-loading-script-services-reference.md#servicesstore-shopwarecoreframeworkdataabstractionlayerfacadesaleschannelrepositoryfacade-saleschannelrepositoryfacade)<br> |
```

2023-01-25 09:45 UTC, sushmangupta approved these changes

2023-01-25 09:45 UTC, merged