NEXT-25152 - Add article regarding watchers
shopware/docs pull request #837
Opened 2023-01-30 14:16 UTC by marcelbrode

2023-01-30 14:30 UTC, jleifeld approved these changes

2023-01-31 07:48 UTC, sushmangupta requested changes
Please update the SUMMARY.md file to make this article visible in the navigation pane.

2023-01-31 07:48 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +or storefront, depending on your change using the following commands:
```suggestion
When developing with Shopware, you probably notice that changes in JavaScript require commands to build the Administration or Storefront, depending on your change using the following commands:
```

2023-01-31 07:48 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +your changes.
```suggestion
This building process is always time-consuming. Alternatively, to speed up the process, Shopware's Production template offers composer commands to enable Hot Module Reloading/watchers to automatically reload and preview your changes.
```

2023-01-31 07:48 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +This procedure does not replace a final build process, when you finished developing your feature.
```suggestion
This procedure doesn't replace the final build process when you finish developing your feature.
```

2023-01-31 07:48 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +a variable set will run the command with the respective change. The following example will run the storefront watcher in production mode:
```suggestion
Using environment variables can also affect Shopware and, therefore, its watchers. Like in Unix, prefixing command calls with a variable set will run the command with the respective change. The following example will run the storefront watcher in production mode:
```

2023-01-31 07:48 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +Toolbar in the Storefront, while its counterpart `APP_ENV=prod` enables production mode and therefore disables such tools.
```suggestion
When using `APP_ENV=dev`, Shopware runs in development mode and provides features for debugging - for example, the Symfony toolbar in the Storefront, while its counterpart `APP_ENV=prod` enables production mode and therefore disables any such tools.
```

2023-01-31 07:48 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +Starting with NodeJS v17.0.0, it prefers IPv6 over IPv4. In some setups, this may cause problems when using watchers.
Please mention what is "it" here.

2023-01-31 08:36 UTC, marcelbrode commented on resources/tooling/cli/using-watchers.md
> +Starting with NodeJS v17.0.0, it prefers IPv6 over IPv4. In some setups, this may cause problems when using watchers.
NodeJS

2023-01-31 09:03 UTC, sushmangupta requested changes

2023-01-31 09:03 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +#### IPV4FIRST
```suggestion
When using `APP_ENV=dev`, Shopware runs in development mode and provides features for debugging - for example, the Symfony toolbar in the Storefront, while its counterpart `APP_ENV=prod` enables production mode and therefore disables any such tools.

#### IPV4FIRST
```

2023-01-31 09:13 UTC, sushmangupta requested changes

2023-01-31 09:13 UTC, sushmangupta commented on SUMMARY.md
> +    * [Using watchers](resources/tooling/cli/using-watchers.md)
```suggestion
    * [Hot Module Reloading using watchers](resources/tooling/cli/using-watchers.md)
```

2023-01-31 09:13 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +## Using watchers
```suggestion
## Watchers
```

2023-01-31 09:13 UTC, sushmangupta commented on resources/tooling/cli/using-watchers.md
> +In case IPv6 causes problems, `IPV4FIRST=1` reverts this behaviour.
```suggestion
Starting with NodeJS v17.0.0, it prefers IPv6 over IPv4. However, in some setups, IPv6 may cause problems when using watchers. In such cases, setting `IPV4FIRST=1` reverts this behavior.
```

2023-01-31 09:16 UTC, sushmangupta approved these changes

2023-01-31 09:17 UTC, merged