NEXT-25207 - Remove development psh commands reference and use composer scripts instead
shopware/docs pull request #848
Opened 2023-02-06 14:34 UTC by keulinho

2023-02-06 14:36 UTC, keulinho commented on guides/plugins/plugins/testing/end-to-end-testing.md
> +The easiest way to clean up your installation is the initialization. Using the command `composer run init` Shopware 6 gets initialized clean and without demo data. Installation of E2E dependencies ca
I'm not sure with all the docker mentioned, what to execute outside or inside and if it is even needed anymore cc @leichteckig can you please check that?

2023-02-06 14:36 UTC, keulinho commented on guides/plugins/apps/local-development/app-development-with-docker.md
> -# App development with docker
removed it as we don't support that anymore without the dev template

2023-02-06 14:52 UTC, shyim requested changes

2023-02-06 14:52 UTC, shyim commented on guides/plugins/plugins/administration/add-custom-field.md
> +{% tab title="Production template" %}
```suggestion
{% tab title="Template" %}
```

2023-02-06 14:52 UTC, shyim commented on guides/plugins/plugins/administration/add-custom-module.md
> +{% tab title="Production template" %}
```suggestion
{% tab title="Template" %}
```

2023-02-06 14:52 UTC, shyim commented on guides/plugins/plugins/administration/add-custom-field.md
> +{% tab title="platform only" %}
```suggestion
{% tab title="platform only (contribute)" %}
```

2023-02-06 14:52 UTC, shyim commented on guides/plugins/plugins/administration/add-custom-module.md
> +{% tab title="platform only" %}
```suggestion
{% tab title="platform only (contribute)" %}
```

2023-02-06 15:11 UTC, keulinho commented on guides/plugins/plugins/administration/add-custom-field.md
> +{% tab title="platform only" %}
i use `platform only (contribution setup)` now

2023-02-07 08:31 UTC, Christian-Rades approved these changes

2023-02-07 13:57 UTC, shyim approved these changes

2023-02-07 14:12 UTC, merged