Fix explanation of asset installation and CSS usage
shopware/docs pull request #852
Opened 2023-02-08 12:00 UTC by dallyger

2023-02-08 16:11 UTC, dallyger commented
The current explanation for theme assets installation is confusing, so I clarified, which command does what exactly.
We had a bug, where the shop owner had run `assets:install` without `theme:compile` and all fonts were missing.
This got only recently documented and was absent before. See here: <https://github.com/shopware/docs/commit/89dfc858cdb49f21cb1566f0f497b5902263ca80>

Also, in this commit: <https://github.com/shopware/docs/commit/38d70edeab538226dba9a73610e3127ff9cb2347>
The documented path for the assets got replaced by the one, that `assets:install` overrides.
The CSS rule loads it from `theme/<theme-id>` instead.

What is the correct use here?

Twig references the bundle (plugin) asset path, while CSS references the theme asset path.

Additionally, none of the mentioned paths were correct. Sometimes the assets were in a subfolder called `assets`, sometimes in `asset` and sometimes the subfolder was missing completely.
I hope, I've fixed those too now.

Maybe someone could double-check the entire document, as I could only fix it to the best of my current knowledge.

2023-04-05 12:52 UTC, tobiasberge requested changes
Hi, thanks for your contribution 🎉  and sorry for my late reply.

There were a couple of changes recently to the way assets work in themes.

You can find an [ADR about the changes here](https://github.com/shopware/platform/blob/trunk/adr/2023-01-10-atomic-theme-compilation.md) as well as the [corresponding change](https://github.com/shopware/platform/commit/cd3a58499c02993267c85097b550b4d07c0fffe4).

We have read your modified article and tested it with a Theme which includes assets.

The following stuff needs adjustment in the documentation:

* Theme assets are no longer saved under `<shopware root>/public/bundles`, all theme assets are saved under `<shopware root>/public/theme`
* Theme assets (images, fonts etc.) are no longer stored inside the same folder as the compiled files (CSS and JS) to avoid duplicating assets, [see ADR "Theme Assets"](https://github.com/shopware/platform/blob/trunk/adr/2023-01-10-atomic-theme-compilation.md#theme-assets), this results in a structure like this:
    ```
    .
    └── theme
        ├── <theme-uuid>
        │   ├── css
        │   │   └── all.css
        │   └── js
        │       └── all.js
        └── <theme-asset-uuid>
            └── asset
                └── your-image.png   
    ```
* Because everything is under `<shopware root>/public/theme`, the command `bin/console assets:install` is not needed anymore and the assets will be copied during `theme:compile`
* To refernce it in the SCSS, we use the variable `$app-css-relative-asset-path`: Traversing up the directory no longer works because the assets are no longer in the same directory.
    ```scss
    body {
        background-image: url('#{$app-css-relative-asset-path}/your-image.png');
    }
    ```
* To reference it inside twig, we use `theme` as `$packageName` parameter in the `asset()` function:
    ```twig
    <img src="{{ asset('/assets/your-image.png', 'theme') }}">
    ```

2023-04-05 13:01 UTC, tobiasberge commented on guides/plugins/themes/add-assets-to-theme.md
> +            └── your-image.png
```suggestion
└── theme
    ├── <theme-uuid>
    │   ├── css
    │   │   └── all.css
    │   └── js
    │       └── all.js
    └── <theme-asset-uuid>
        └── asset
            └── your-image.png   
```

2023-04-05 13:01 UTC, tobiasberge commented on guides/plugins/themes/add-assets-to-theme.md
> +<img src="{{ asset('bundles/<your-plugin-name>/assets/your-image.png', 'asset') }}">
```suggestion
<img src="{{ asset('/assets/your-image.png', 'theme') }}">
```

2023-04-05 13:01 UTC, tobiasberge commented on guides/plugins/themes/add-assets-to-theme.md
> +    background-image: url("../assets/your-image.png");
```suggestion
    background-image: url('#{$app-css-relative-asset-path}/your-image.png');
```

2023-04-13 15:27 UTC, tobiasberge approved these changes

2023-04-13 15:36 UTC, ssltg approved these changes

2023-04-13 15:36 UTC, sushmangupta requested changes

2023-04-13 15:36 UTC, sushmangupta commented on guides/plugins/themes/add-assets-to-theme.md
> +Next, please run the command `bin/console theme:compile`. The assets from the path defined in the `theme.json` file will be copied by the `theme:compile` command to `<shopware root>/public/theme/<the
```suggestion
Next, run the command `bin/console theme:compile`. The assets from the path defined in the `theme.json` file will be copied by the `theme:compile` command to `<shopware root>/public/theme/<theme-asset-uuid>` along with the compiled CSS and JS, which are stored in a separate folder.
```

2023-04-13 15:36 UTC, sushmangupta commented on guides/plugins/themes/add-assets-to-theme.md
>  In SCSS you can link to the asset like the following:
```suggestion
In SCSS, you can link to the asset like the following:
```

2023-04-13 15:37 UTC, sushmangupta approved these changes

2023-04-13 15:37 UTC, merged