NEXT-11357 - Add documentation for native lazy loading
shopware/docs pull request #866
Opened 2023-02-20 10:22 UTC by tobiasberge

Add documentation for native lazy loading for sw_thumbnail in 6.5

2023-02-20 10:31 UTC, ssltg approved these changes

2023-02-20 10:31 UTC, mboelt commented
@mboelt @sdenter FYI

2023-03-01 09:10 UTC, tobiasberge commented
Target needs to change to master because master is not 6.5 RC

2023-03-01 09:27 UTC, sushmangupta requested changes

2023-03-01 09:27 UTC, sushmangupta commented on guides/plugins/plugins/storefront/use-media-thumbnails.md
> +This will generate the output below:
```suggestion
This will generate the below output:
```

2023-03-01 09:27 UTC, sushmangupta commented on guides/plugins/plugins/storefront/use-media-thumbnails.md
> +* When images rendered by `sw_thumbnail` are within a container which is hidden by CSS via `display: none`.
```suggestion
* When multiple `sw_thumbnail` elements occur on one page and are not in the initial viewport.
* When images rendered by `sw_thumbnail` are within a container hidden by CSS via `display: none`.
```

2023-03-01 09:38 UTC, sushmangupta approved these changes

2023-03-01 09:39 UTC, merged