NEXT-25314 - Add docs for template priority in apps
shopware/docs pull request #880
Opened 2023-03-07 12:09 UTC by shyim

2023-03-13 15:38 UTC, bojanrajh approved these changes

2023-03-15 08:24 UTC, sushmangupta requested changes

2023-03-15 08:24 UTC, sushmangupta commented on guides/plugins/apps/storefront/README.md
> +You may want that your templates are loaded before other extensions or after extensions. So you can define a `load-priority` inside your `manifest.xml`. The default value is 0 and positive numbers yo
```suggestion
You may want your templates loaded before or after other extensions. To do so, you can define a `load-priority` inside your `manifest.xml`. The default value to this is 0, with positive numbers your template will be loaded earlier, and with negative numbers later.
```

2023-03-15 08:24 UTC, sushmangupta approved these changes

2023-03-15 08:24 UTC, merged