added a "Dummy App" entry
shopware/docs pull request #895
Opened 2023-03-14 13:33 UTC by Swvla

How to create a dummy app and why etc.

The following basic requirements must be met:
- as a basis, the manufacturer contract must be accepted
- The STP contract must be additionally concluded with the technology 
- The app needs a login page as iFrame  
- The company logo and the manifest xml file are sufficient for the dummy app 
- The iFrame can be called via a PHP index or the URL
- A custom UI may be used

2023-03-15 08:20 UTC, Christian-Rades requested changes

2023-03-15 08:20 UTC, Christian-Rades commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +### Dummy App
We should consider using a more fitting name.

2023-03-15 08:20 UTC, Christian-Rades commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +With a dummy app you can offer your middleware in the store, if you only use the APIs of Shopware.
I think `API service` is a more fitting description than middleware in this context.

2023-03-15 08:20 UTC, Christian-Rades commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +* The STP contract must be additionally concluded with the technology
```suggestion
* The STP(Shopware technology partner) contract must be additionally concluded with the technology 
```

2023-03-15 08:20 UTC, Christian-Rades commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +* The app needs a login page as iFrame
```suggestion
* The app needs to provide a login page as an iFrame  
```

2023-03-15 08:20 UTC, Christian-Rades commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +* The iFrame can be called via a PHP index or the URL
What precisley do you mean by PHP index?

2023-03-15 08:20 UTC, Christian-Rades commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +* A custom UI may be used
I think this can be reworded as something like:

The app UI can be provided through the iFrame mentioned above.

2023-03-21 09:32 UTC, sushmangupta requested changes
I would like to propose this updated content after talking with Alliance team member, Mandy. @Swvla / @sdenter please review this information and feel free to make any changes

### Service Solution App (SSA)

With SSA you can offer your middleware in the store, if you only use the APIs of Shopware.
We recommend you to develop this as a cloud app. The app will be available for both cloud and on-premises customers. The following basic requirements must be met:

* The manufacturer contract must be accepted.

* The STP(Shopware technology partner) contract must be additionally concluded with the technology.

* Add the company logo and the manifest file. For more support, refer to our [App Base Guide](/docs/guides/plugins/apps/app-base-guide#manifest-file).

{% hint style="warning" %}
The name of your app that you provide in the manifest file needs to match the folder name of your app.
{% endhint %}

* The app needs to provide a login page as an iFrame.

* The iFrame can be accessed by URL or by the barcode generated by [PHP index](https://gist.github.com/samt/1175098).

* The app UI can be provided through the iFrame mentioned above.

{% hint style="warning" %}
SSA needs a minimum function, for instance a Landingpage where customers can add their names and addresses.
{% endhint %}

* Upload your app to your Account

* Submit your app for automatic and manual code review

* Launch your successfully tested app in our store

2023-03-21 09:57 UTC, sdenter approved these changes
Sounds good for me!

2023-03-22 12:47 UTC, sushmangupta requested changes
#Service Solution App (SSA)

With SSA, you can offer API services for apps in the store. We recommend you develop this as a cloud app. The app will be available for both cloud and on-premises customers. The following basic requirements must be met:

* The manufacturer contract must be accepted.

* The STP (Shopware technology partner) contract must be additionally concluded with the technology.

* Add the company logo and the manifest file. For more support, refer to our [App Base Guide](https://github.com/docs/guides/plugins/apps/app-base-guide#manifest-file).

{% hint style="warning" %}
The name of your app that you provide in the manifest file needs to match the folder name of your app.
{% endhint %}

* The app needs to provide a login page as an iFrame.

* The iFrame can be accessed by URL or the barcode generated by [PHP index](https://gist.github.com/samt/1175098).

* The app UI can be provided through the iFrame mentioned above.

{% hint style="warning" %}
SSA needs a minimum function, for instance, a landing page where customers can add their names and addresses.
{% endhint %}

* Upload your app to your Account.

* Submit your app for automatic and manual code review.

* Launch your successfully tested app in our store.

2023-03-22 12:48 UTC, sushmangupta requested changes
#Service Solution App (SSA)

With SSA, you can offer API services for apps in the store. We recommend you develop this as a cloud app. The app will be available for both cloud and on-premises customers. The following basic requirements must be met:

* The manufacturer contract must be accepted.

* The STP (Shopware technology partner) contract must be additionally concluded with the technology.

* Add the company logo and the manifest file. For more support, refer to our [App Base Guide](https://github.com/docs/guides/plugins/apps/app-base-guide#manifest-file).

{% hint style="warning" %}
The name of your app that you provide in the manifest file needs to match the folder name of your app.
{% endhint %}

* The app needs to provide a login page as an iFrame.

* The iFrame can be accessed by URL or the barcode generated by [PHP index](https://gist.github.com/samt/1175098).

* The app UI can be provided through the iFrame mentioned above.

{% hint style="warning" %}
SSA needs a minimum function, for instance, a landing page where customers can add their names and addresses.
{% endhint %}

* Upload your app to your Account.

* Submit your app for automatic and manual code review.

* Launch your successfully tested app in our store.

2023-03-22 13:02 UTC, sushmangupta approved these changes

2023-04-05 07:08 UTC, Christian-Rades approved these changes

2023-04-05 07:47 UTC, sushmangupta requested changes

2023-04-05 07:47 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +* The iFrame can be accessed by URL or the barcode generated by PHP index.
```suggestion
* The iFrame can be accessed by URL or the barcode generated by [PHP index](https://gist.github.com/samt/1175098).
```

2023-04-05 07:47 UTC, sushmangupta commented on resources/guidelines/testing/store/quality-guidelines-apps/README.md
> +* Add the company logo and the manifest file. For more support, refer to our App Base Guide.
```suggestion
* Add the company logo and the manifest file. For more support, refer to our [App Base Guide](/docs/guides/plugins/apps/app-base-guide.md).
```

2023-04-05 07:47 UTC, sushmangupta approved these changes

2023-04-05 07:47 UTC, merged