Update Commands Reference for Shopware 6.5 & Symfony 6.2
shopware/docs pull request #954
Opened 2023-05-11 17:39 UTC by sandoba

- removed outdated CLI commands from previous versions of Shopware / Symfony (e.g. SwiftMailer, Enqueue)
- added new CLI commands of Shopware / Symfony
- added missing aliases and descriptions for some commands
- updated descriptions for some commands to use more consistent language

Additional default CLI commands of Symfony 6.2 that could also be added in this file if useful in the Shopware context: "cache:pool:invalidate-tags", "debug:dotenv", "debug:validator", "dotenv:dump", "server:dump", "server:log", "translation:extract", "translation:pull", "translation:push"

2023-05-12 10:45 UTC, shyim approved these changes

2023-05-17 09:05 UTC, sushmangupta requested changes

2023-05-17 09:05 UTC, sushmangupta commented on resources/references/core-reference/commands-reference.md
> +| `feature:dump` | \[administration:dump:features\] Creates a json file with feature config for js testing and hot reloading capabilities |
```suggestion
| `feature:dump` | \[administration:dump:features\] Creates a JSON file with feature config for JS testing and hot reloading capabilities |
```

2023-05-17 09:05 UTC, sushmangupta commented on resources/references/core-reference/commands-reference.md
> +| `http:cache:warm:up` | Warms up the http cache |
```suggestion
| `http:cache:warm:up` | Warms up the HTTP cache |
```

2023-05-17 09:05 UTC, sushmangupta commented on resources/references/core-reference/commands-reference.md
> +| `import:entity` | Imports entities from a csv file |
```suggestion
| `import:entity` | Imports entities from a CSV file |
```

2023-05-17 09:06 UTC, sushmangupta approved these changes

2023-05-17 09:07 UTC, merged